devstream-io/devstream

- .github/workflows/golangci-lint.yml
- CONTRIBUTING.md
- cmd/argocd/main.go
- cmd/argocdapp/main.go
- cmd/devstream/main.go
- cmd/githubactions/main.go
- internal/pkg/githubactions/githubactions.go
- add a new GitHub Actions workflow to use `golangci-lint` for code style check and static code check
- update the CONTRIBUTING.md documentation with git commit message guidelines and code style guide
- minor refactor according to `golangci-lint` result
PR and pushes to the main branch will be checked against `golangci-lint` Github Actions for code style and potential issues.
> Code style improvement

- .gitignore
- Makefile
- cmd/devstream/install.go
- internal/pkg/backend/backend.go
- internal/pkg/backend/local/local.go
- internal/pkg/statemanager/manager.go
- internal/pkg/statemanager/manager_test.go
- internal/pkg/statemanager/state.go
state management support
#16 
#24 
- devstream.state
```yaml
argocd:
name: argocd
version: v0.0.1
dependencies: []
status: running
lastOperation:
action: install
time: 2021-12-07_20:59:09
metadata:
key: value
```
> feat: state management support

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/question.md
- .gitignore
- Makefile
- cmd/devstream/install.go
- internal/pkg/backend/backend.go
- internal/pkg/backend/local/local.go
- internal/pkg/statemanager/manager.go
- internal/pkg/statemanager/manager_test.go
- internal/pkg/statemanager/state.go
just modify author's info with commit-915bd1e
> modify author's info with commit-915bd1e

- go.mod
- go.sum
- internal/pkg/download/download.go
- internal/pkg/download/download_test.go
- internal/pkg/download/manager.go
- internal/pkg/download/releaseinfo.go
- internal/pkg/plugin/plugin.go
#17 
plugin management support,
1  modified
4 created
> plugin management support

- README.md
Note: please complete **_ALL_** items in the following checklist, and **_remove this section before submitting_**.
- I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- This PR is using a `label` (bug, feature, etc.)
- My code has the necessary comments and documentation (if needed).
- I have added relevant tests
- I will remove this section (**⚠️ Pre-Checklist**) when submitting this PR
Will this PR close any open issues? If yes, would you please mention the issue(s) here?
> docs: change CLI name

- cmd/argocd/main.go
- cmd/argocdapp/main.go
- cmd/devstream/install.go
- cmd/githubactions/main.go
- go.mod
- go.sum
- internal/pkg/argocd/install.go
- internal/pkg/argocdapp/install.go
- internal/pkg/githubactions/install.go
- internal/pkg/plan/plan.go
- internal/pkg/plan/plan_test.go
- internal/pkg/plugin/plugin.go
- internal/pkg/statemanager/manager.go
- internal/pkg/statemanager/manager_test.go
- internal/pkg/statemanager/state.go
Adding a "action calculation" feature to determine the next action based on the current States of the environment and the input Config.
- [* ] This is a breaking change.
see #29 
#29
> an "action calculation" feature to determine the next action.

- cmd/devstream/init.go
- cmd/devstream/install.go
- internal/pkg/plan/plan.go
- internal/pkg/pluginmanager/downloader.go
> Refactor downloader

- docs/argocd_app_plugin.md
- docs/argocd_plugin.md
- docs/github_actions_plugin.md
doc: fine-tune some small issues such as letter case
> doc: fine-tune some small issues such as letter case

- docs/argocd_app_plugin.md
- docs/argocd_plugin.md
- docs/creating_a_plugin.md
- docs/github_actions_plugin.md
Plugins documentation updated:
- how to create a plugin
- doc for GitHub Actions plugin
- doc for ArgoCD plugin
- doc for ArgoCD App plugin
https://github.com/merico-dev/stream/issues/6
> doc: Plugins Documentation

- internal/pkg/planmanager/plan.go
- internal/pkg/planmanager/result.go
> fix: #54 new plan error

- internal/pkg/planmanager/result.go
Supplement the fix for #54
#54 
@lfbdev Please help to review
> fix: Supplement the fix for #54

- .github/workflows/pr-builder.yml
caching go dependencies to speed up workflows
> feat: caching go dependencies to speed up workflows

- cmd/devstream/main.go
- internal/pkg/githubactions/githubactions.go
- internal/pkg/githubactions/golang/templates.go
- internal/pkg/githubactions/install.go
- internal/pkg/githubactions/reinstall.go
- internal/pkg/githubactions/uninstall.go
- Improve some error handling & log format.
- Fix the nil pointer dereference error below:
> fix: some tips with githubactions for golang

- internal/pkg/argocdapp/argocdapp.go
- internal/pkg/argocdapp/install.go
- internal/pkg/argocdapp/reinstall.go
- internal/pkg/argocdapp/uninstall.go
do some refactor with argocdapp plugin
> refactor: do some refactor with argocdapp plugin

- internal/pkg/githubactions/githubactions.go
- internal/pkg/pluginmanager/manager.go
1. There is no printing while downloading 
2. SHA is necessary for del or update 
Before:
After:
#50
> fix: add downloading tips and add SHA for updating github files

- internal/pkg/githubactions/githubactions.go
fix: invalid memory address or nil pointer dereference at getFileSHA()
fix #84 
@IronCore864 @lfbdev Please take a review.
> fix: #84 invalid memory address or nil pointer dereference at getFileSHA()

- internal/pkg/planmanager/result.go
- internal/pkg/statemanager/state.go
fix: #82 statemanager delete a State when uninstall failed
fix: #82 
/kind bug
/cc @IronCore864 @lfbdev
> fix: #82 statemanager delete a State when uninstall failed

- internal/pkg/githubactions/githubactions.go
- internal/pkg/pluginmanager/downloader_test.go
sha lost in Deleteworkflow,  delete option failed
#81 
> sha lost in Deleteworkflow

- cmd/argocd/main.go
- cmd/argocdapp/main.go
- cmd/devstream/init.go
- cmd/githubactions/main.go
- internal/pkg/pluginengine/plugin.go
- internal/pkg/pluginmanager/manager.go
- internal/pkg/statemanager/state.go
logs format improved
fix: #89 
fix: #90
> fix: #89 #90 - logs format improved

- cmd/devstream/install.go
- internal/pkg/pluginmanager/manager.go
fix some grammatical errors in logs
> Fix: fix some grammatical errors in logs

- internal/pkg/container/concurrentmap/concurrentmap.go
- internal/pkg/planmanager/plan.go
- internal/pkg/planmanager/result.go
- internal/pkg/statemanager/manager.go
- internal/pkg/statemanager/manager_test.go
- internal/pkg/statemanager/state.go
- internal/pkg/statemanager/states.go
> feat: adding ConcurrentMap

- CODE_OF_CONDUCT.md
Code of conduct documentation, adapted from Rust's code of conduct.
Closes #77
> doc: code of conduct

- go.mod
- go.sum
- internal/pkg/pluginmanager/manager.go
- internal/pkg/pluginmanager/pbdownloader.go
add progress bar  when executing download plugins
#98
> progress bar for download

- .gitignore
- cmd/devstream/main.go
- internal/pkg/backend/local/local.go
- internal/pkg/plugin/githubactions/githubactions.go
- internal/pkg/pluginengine/plugin.go
- internal/pkg/pluginmanager/downloader.go
- internal/pkg/pluginmanager/manager.go
Add a Parameter -p (--plugins-dir)
fix: #104
> Feat: Add a Parameter -p (--plugins-dir)

- cmd/devstream/apply.go
- cmd/devstream/install.go
- cmd/devstream/main.go
- go.mod
- go.sum
change dtm command from 'install' to 'apply'
#48
> change command 'install' to 'apply'

- internal/pkg/pluginmanager/manager.go
- internal/pkg/pluginmanager/md5.go
- internal/pkg/pluginmanager/pbdownloader.go
add md5 check on local file and remote file
#103  add content-md5 check on local file and remote file
> check file content md5

- internal/pkg/pluginengine/apply.go
> bug: hot fix for issue 119

- examples/config.yaml
- internal/pkg/plugin/githubactions/golang/templates.go
- internal/pkg/plugin/githubactions/jobs.go
auto comment by githubacions, when coverage done
#133
> auto comment by githubacions

- docs/argocd_plugin.md
- docs/kube-prometheus_plugin.md
- examples/config.yaml
- internal/pkg/util/helm/helm.go
- internal/pkg/util/helm/param.go
expose more params with the plugins used helm
> Feat: exposed more params with the plugins used helm

- internal/pkg/plugin/argocd/ishealthy.go
- internal/pkg/plugin/kubeprometheus/ishealthy.go
- internal/pkg/util/k8s/k8s.go
Feat: health-check for kube-prometheus
> Feat: health-check for kube-prometheus

- cmd/devstream/init.go
- cmd/devstream/verify.go
- internal/pkg/configloader/config.go
- internal/pkg/configloader/validation.go
- internal/pkg/pluginengine/apply.go
- internal/pkg/pluginengine/check.go
- internal/pkg/pluginengine/delete.go
Adding config validation for dtm.
(Options validations with all plugins will be implemented in another pr)
> Feat: Adding config validation for dtm

- internal/pkg/configloader/validation.go
- internal/pkg/plugin/argocd/install.go
- internal/pkg/plugin/argocd/ishealthy.go
- internal/pkg/plugin/argocd/reinstall.go
- internal/pkg/plugin/argocd/uninstall.go
- internal/pkg/plugin/argocd/validation.go
- internal/pkg/plugin/argocdapp/install.go
- internal/pkg/plugin/argocdapp/ishealthy.go
- internal/pkg/plugin/argocdapp/reinstall.go
- internal/pkg/plugin/argocdapp/uninstall.go
- internal/pkg/plugin/argocdapp/validation.go
- internal/pkg/plugin/githubactions/githubactions.go
- internal/pkg/plugin/githubactions/jobs.go
- internal/pkg/plugin/githubactions/validation.go
- internal/pkg/plugin/githubactions/workflow.go
- internal/pkg/plugin/kubeprometheus/install.go
- internal/pkg/plugin/kubeprometheus/ishealthy.go
- internal/pkg/plugin/kubeprometheus/reinstall.go
- internal/pkg/plugin/kubeprometheus/uninstall.go
- internal/pkg/plugin/kubeprometheus/validation.go
- internal/pkg/plugin/trellogithub/trellogithub.go
- internal/pkg/plugin/trellogithub/validation.go
- internal/pkg/plugin/trellogithub/workflowhelper.go
- internal/pkg/util/helm/validation.go
Adding config validation for all plugins
> Feat: Adding config validation for all plugins

- internal/pkg/plugin/reposcaffolding/github/golang/install.go
- internal/pkg/util/downloader/downloader.go
- internal/pkg/util/downloader/downloader_suite_test.go
- internal/pkg/util/downloader/downloader_test.go
- internal/pkg/util/github/github.go
- internal/pkg/util/github/github_suite_test.go
- internal/pkg/util/github/github_test.go
Adding util/github & util/downloader
> Feat: Implement util/github for plugin github-repo-scaffolding-golang

- .gitignore
- docs/github-repo-scaffolding-golang_plugin.md
- examples/config.yaml
- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- internal/pkg/plugin/reposcaffolding/github/golang/install.go
- internal/pkg/plugin/reposcaffolding/github/golang/param.go
- internal/pkg/plugin/reposcaffolding/github/golang/validation.go
- internal/pkg/util/downloader/downloader.go
- internal/pkg/util/github/github.go
- internal/pkg/util/github/github_test.go
- internal/pkg/util/zip/zip.go
- internal/pkg/util/zip/zip_suit_test.go
- internal/pkg/util/zip/zip_test.go
Implementing Install() for github-reposcaffolding-golang plugin
> Feat: Implementing Install() for github-reposcaffolding-golang plugin

- Makefile
- build/package/Dockerfile
- build/package/build_linux_amd64.sh
- internal/pkg/version/version.go
add global var VERSION to control build version 
#155 
> Makefile version improve

- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- internal/pkg/plugin/reposcaffolding/github/golang/install.go
- internal/pkg/util/downloader/downloader.go
- internal/pkg/util/downloader/downloader_test.go
- internal/pkg/util/github/github.go
- internal/pkg/util/zip/zip.go
Let github-repo-scaffolding-golang the the main branch code of the template repo
> Feat: Let github-repo-scaffolding-golang the the main branch code of the template repo

- Makefile
- cmd/devstream/main.go
- examples/config.yaml
- internal/pkg/log/log.go
- internal/pkg/log/logwrapper.go
- internal/pkg/pluginengine/apply.go
- internal/pkg/pluginengine/helper.go
- internal/pkg/util/zip/zip.go
- version changed to 0.0.2, for integration tests
- Trello plugin is commented out from the example config file
- unzipping now logs to debug level (instead of info)
- `make e2e-up` / `make e2e-down`
- ASCII art in `dtm help` (thanks to @daniel-hutao)
- add a logging format for "separator"
> Chore: Quality-of-Life Improvements

- cmd/devstream/main.go
- go.mod
- go.sum
- internal/pkg/util/trello/trello.go
- internal/pkg/util/trello/trello_suit_test.go
- internal/pkg/util/trello/trello_test.go
> Feat: Adding trello util

- build/package/build_linux_amd64.sh
Fix: kube-prometheus pkg name error
> Fix: kube-prometheus pkg name error

- internal/pkg/plugin/trellogithub/install.go
- internal/pkg/plugin/trellogithub/reinstall.go
need more print  for each step
need more print  for each step while plugin occupies some time
#161 
> update log statements

- internal/pkg/version/version.go
Fix: update the comment with the VERSION
> Fix: update the comment with the VERSION

- Makefile
- README.md
- examples/config.yaml
Plugin cross-platform build doesn't work; updating Makefile accordingly.
> bug: plugin cross-arch build does not work

- internal/pkg/plugin/reposcaffolding/github/golang/install.go
- pkg/util/github/download.go
- pkg/util/github/github.go
Fix: workpath clear for repo-scaffolding
> Fix: workpath clear for repo-scaffolding

- docs/argocd_plugin.md
- docs/kube-prometheus_plugin.md
- pkg/util/helm/validation.go
Feat: Adding Defaults() to util/helm
> Feat: Adding Defaults() to util/helm

- internal/pkg/configloader/config.go
- internal/pkg/planmanager/change.go
- internal/pkg/planmanager/plan_apply.go
- internal/pkg/planmanager/plan_delete.go
- internal/pkg/planmanager/plan_helper.go
- internal/pkg/planmanager/result.go
- internal/pkg/pluginengine/delete.go
- internal/pkg/statemanager/manager.go
- internal/pkg/statemanager/manager_suit_test.go
- internal/pkg/statemanager/manager_test.go
- internal/pkg/statemanager/state.go
- internal/pkg/statemanager/states_map.go
- pkg/util/mapz/concurrentmap/concurrentmap.go
- pkg/util/mapz/concurrentmap/concurrentmap_suit_test.go
- pkg/util/mapz/concurrentmap/concurrentmap_test.go
- Fix state delete failed error
- Fix Statesmap issue
- Fix Concurrentmap issue
- Add UT for Concurrentmap and Statesmap
> Fix: deleting state failed

- pkg/util/helm/helm.go
Turning on Atomic flag with Helm style plugins
See #181 for more info.
> Feat: Turning on Atomic flag with Helm style plugins

- examples/config.yaml
- internal/pkg/plugin/githubactions/golang/install.go
- internal/pkg/plugin/githubactions/golang/ishealthy.go
- internal/pkg/plugin/githubactions/golang/jobs.go
- internal/pkg/plugin/githubactions/golang/options.go
- internal/pkg/plugin/githubactions/golang/reinstall.go
- internal/pkg/plugin/githubactions/golang/render.go
- internal/pkg/plugin/githubactions/golang/templates.go
- internal/pkg/plugin/githubactions/golang/uninstall.go
1. Remove “jobs” section , as it doesn’t do anything.
2. Support default config if there is no config
#185 
> remove 'job' item, support default config

- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- pkg/util/github/branch.go
- pkg/util/github/commit.go
- pkg/util/github/file.go
- pkg/util/github/pullrequest.go
Feat: Create multiple files in one single commit
see https://github.com/daniel-hutao/golang-demo for more info
> Feat: Create multiple files in one single commit

- docs/github-repo-scaffolding-golang_plugin.md
- internal/pkg/plugin/reposcaffolding/github/golang/ishealthy.go
- internal/pkg/plugin/reposcaffolding/github/golang/reinstall.go
- internal/pkg/plugin/reposcaffolding/github/golang/uninstall.go
- pkg/util/github/repo.go
Add other features (uninstall / reinstall) for "Golang Repo Scaffolding"
uninstall: remove the repo
reinstall: remove the repo and recreate the repo
#191
> Feat: Golang Repo Scaffolding: implement other interfaces (uninstall/reinstall)

- README.md
Adding "Quick Install" at README.md
> Docs: Adding "Quick Install" at README.md

- cmd/argocd/main.go
- cmd/argocdapp/main.go
- cmd/devlake/main.go
- cmd/devstream/delete.go
- cmd/githubactions/golang/main.go
- cmd/githubactions/nodejs/main.go
- cmd/githubactions/python/main.go
- cmd/kubeprometheus/main.go
- cmd/reposcaffolding/github/golang/main.go
- cmd/trellogithub/main.go
- go.mod
- internal/pkg/plugin/argocd/create.go
- internal/pkg/plugin/argocd/delete.go
- internal/pkg/plugin/argocd/read.go
- internal/pkg/plugin/argocd/update.go
- internal/pkg/pluginengine/check.go
- internal/pkg/pluginengine/delete.go
- internal/pkg/pluginengine/helper.go
- internal/pkg/pluginengine/plugin.go
ArgoCD return values & pluginengine refactor
See #194 for more info
> Feat: ArgoCD return values & pluginengine refactor

- go.mod
- internal/pkg/planmanager/plan_helper.go
- internal/pkg/planmanager/planmanager_test.go
- internal/pkg/planmanager/result.go
- internal/pkg/statemanager/manager.go
- internal/pkg/statemanager/manager_test.go
- internal/pkg/statemanager/state.go
- internal/pkg/statemanager/states_map.go
refactor the statemanager package
> Feat: refactor the statemanager package

- README.md
- cmd/jenkins/main.go
- docs/jenkins_plugin.md
- examples/config.yaml
- internal/pkg/planmanager/planmanager_test.go
- internal/pkg/plugin/jenkins/create.go
- internal/pkg/plugin/jenkins/delete.go
- internal/pkg/plugin/jenkins/params.go
- internal/pkg/plugin/jenkins/read.go
- internal/pkg/plugin/jenkins/state.go
- internal/pkg/plugin/jenkins/update.go
- internal/pkg/plugin/jenkins/validation.go
Adding Jenkins plugin support
close #11
> Feat: Adding Jenkins plugin support

- internal/pkg/plugin/argocd/update.go
- internal/pkg/plugin/jenkins/update.go
- internal/pkg/plugin/kubeprometheus/update.go
Simplify the Update() with helm-style plugins.
> Feat: simplify the Update() with helm-style plugins.

- Makefile
- build/package/build_linux_amd64.sh
- internal/pkg/plugin/jenkins/create.go
- internal/pkg/plugin/jenkins/params.go
- internal/pkg/plugin/jenkins/precreate.go
- pkg/util/helm/helm.go
- pkg/util/helm/param.go
- pkg/util/k8s/rbac.go
- pkg/util/k8s/storage.go
Adding Jenkins plugin pre-create logic
> Feat: Adding Jenkins plugin pre-create logic

- cmd/devstream/apply.go
- docs/plugins/jenkins_plugin.md
- examples/config.yaml
- internal/pkg/plugin/jenkins/precreate.go
- internal/pkg/pluginengine/change.go
- internal/pkg/pluginengine/cmd_apply.go
- internal/pkg/pluginengine/cmd_verify.go
Feat: refactor the jenkins data directory logic
> Feat: refactor the jenkins data directory logic

- internal/pkg/plugin/githubactions/common.go
- internal/pkg/plugin/reposcaffolding/github/golang/read.go
bugfix BuildState of scaffolding and githubactions
#213 
> Bugfix: resource state bugfix

- internal/pkg/plugin/argocd/create.go
- internal/pkg/plugin/jenkins/create.go
- internal/pkg/plugin/kubeprometheus/create.go
Fix: the return error is changed by the defer function
close #222
> Fix: the return error is changed by the defer function

- docs/plugins/github-repo-scaffolding-golang_plugin.md
- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- internal/pkg/plugin/reposcaffolding/github/golang/read.go
- internal/pkg/pluginengine/change_helper.go
- fix a bug for plugin Golang repo scaffolding (repo owner lower/upper case)
- add more logging in plugin engine for easier debugging
> Bug fix for v0.2.0

- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- pkg/util/github/github.go
Fix: plugin github-repo-scaffolding-golang `branch` doesn't take effect.
1. Fix #237
2. Fix #238
#237 #238
I've already tested the new code, the 2 bugs have been fixed.
- create
- delete
> Fix: plugin github-repo-scaffolding-golang `branch` doesn't take effect.

- internal/pkg/backend/backend.go
- internal/pkg/backend/local/local.go
- internal/pkg/statemanager/manager.go
Fix: `dtm init xxx` created the state file
close #240
> Fix: `dtm init xxx` created the state file

- SECURITY.md
Security document, which is a requirement of CNCF incubating.
> doc: add security doc

- README.md
- docs/plugins/trello-github-integ_plugin.md
- examples/config.yaml
Feat: adding more comment at config.yaml
close #254
> Feat: adding more comment at config.yaml

- go.mod
- internal/pkg/plugin/githubactions/golang/read.go
- internal/pkg/plugin/githubactions/nodejs/read.go
- internal/pkg/plugin/githubactions/python/read.go
- internal/pkg/plugin/reposcaffolding/github/golang/read.go
- pkg/util/github/repo.go
- pkg/util/github/workflow.go
See issue #263
```bash
tiexin@MBA ~/work/stream $ ./dtm-darwin-arm64 apply
2022-03-04 10:41:27 ℹ [INFO]  Apply started.
2022-03-04 10:41:27 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-03-04 10:41:31 ℹ [INFO]  Tool < go-webapp-repo > state found but it seems the tool isn't created, will be created.
2022-03-04 10:41:31 ℹ [INFO]  Tool < golang-demo-actions > state found but it seems the tool isn't created, will be created.
Enter a value (Default is n): n
```
> bug: github actions and repo scaffolding apply error after deleting repo

- README.md
- docs/README_zh.md
- docs/quickstart_en.md
- docs/quickstart_zh.md
docs: quick start for Chinese version
> docs: quick start for Chinese version

- README.md
- docs/plugins/argocdapp_plugin.md
- docs/plugins/githubactions-golang_plugin.md
- docs/plugins/githubactions-nodejs_plugin.md
- docs/plugins/githubactions-python_plugin.md
- docs/plugins/trello-github-integ_plugin.md
- examples/quickstart.yaml
- internal/pkg/configloader/config.go
- internal/pkg/configloader/configloader_test.go
- internal/pkg/configloader/validation.go
- add "dependsOn" in the documentation (optional)
- dependency check during loading configuration
This PR prepares for the implementation of dependency sort.
> feat: add "dependsOn" in config, add config dependency check

- README.md
- cmd/devstream/delete.go
- cmd/devstream/main.go
- internal/pkg/pluginengine/change.go
- internal/pkg/pluginengine/change_helper.go
- internal/pkg/pluginengine/cmd_delete.go
- internal/pkg/pluginengine/pluginengine_test.go
1. to delete everything defined in config
2. ignore state in devstream.state file
3.  --force, no shorthand
#278
> feat: add 'dtm delete --force' for deleting everything

- CONTRIBUTING.md
- docs/development_workflow.md
A basic `Development Workflow` for new contributors.
> 📖  A basic Development Workflow for new contributors.

- internal/pkg/pluginengine/change.go
- internal/pkg/pluginengine/change_helper.go
fix: the logic with state deleting error
> 🐞 the logic with state deleting error

- pkg/util/log/logwrapper.go
Note: please complete **_ALL_** items in the following checklist, and **_remove this section before submitting_**.
- I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- This PR is using a `label` (bug, feature, etc.)
- My code has the necessary comments and documentation (if needed).
- I have added relevant tests
- I will remove this section (**⚠️ Pre-Checklist**) when submitting this PR
Will this PR close any open issues? If yes, would you please mention the issue(s) here?
Any other …
> revert: "feat: add log stack print for error (#283)"

- internal/pkg/plugin/argocd/update.go
- internal/pkg/plugin/jenkins/update.go
- internal/pkg/plugin/kubeprometheus/update.go
- pkg/util/k8s/static.go
fix: helm-style plugins update failed with ns error
close #286
> fix: helm-style plugins update failed with ns error

- pkg/util/log/logwrapper.go
test entrance is not main.main, so need to deal with this senario
#281
> fix: log stack raises errors when test cases run

- internal/pkg/plugin/reposcaffolding/github/golang/create.go
- internal/pkg/plugin/reposcaffolding/github/golang/delete.go
- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- pkg/util/github/repo.go
clean the repo created when `Create` failed
> feat(repo-scaffolding): clean the repo created when `Create` failed

- CONTRIBUTING.md
- docs/contributor_ladder_growth_programs.md
Define "Contributor Ladder Growth Programs"
> 📖 define "Contributor Ladder Growth Programs"

- internal/pkg/pluginengine/change_helper.go
fix: interface conversion panic
> fix: interface conversion panic

- internal/pkg/plugin/githubactions/golang/templates.go
There is no blank between "path:" and "coverage.out"
1. no blank
2. no PR when push directly 
#295 
#298
> fix: modify githubactions template, add blank, support  push-main without PR 

- README.md
Signed-off-by: Underwood-M <dongfanghuifan@gmail.com>
doc: fix flux case problem
> doc: fix flux case problem

- README.md
- docs/best_practices/gitops.md
- docs/plugins/argocd_plugin.md
- docs/plugins/devlake_plugin.md
- docs/plugins/github-repo-scaffolding-golang_plugin.md
- docs/plugins/githubactions-golang_plugin.md
- docs/plugins/jenkins_plugin.md
- docs/plugins/jira-github-integ_plugin.md
- docs/plugins/kube-prometheus_plugin.md
- docs/plugins/openldap_plugin.md
- examples/gitops.yaml
feat: best practice for gitops toolchain
I have tested this `devops.yaml` and can successfully deploy all tools, but there is no guarantee that the whole process is reasonable enough. 
For example, argocdapp is not associated with repo-scaffolding. So I didn't write the `Check the Results` section in a hurry either. 
I'll spend some more time refining this toolchain later.
> feat: best practice for gitops toolchain

- OWNERS
- README.md
- internal/pkg/plugin/openldap/OWNERS
1. adding OWNERS files
2. adding the `community meeting` info at README
> 📖: adding OWNERS & "community meeting info"

- pkg/util/github/repo.go
Signed-off-by: warren830 <yingchu.chen@merico.dev>
Added error check before checking response status
closes #302 
Check response status before error check, response might be nil can cause panic
Added non '404' error check before response status check
> added error check before checking response.status

- docs/plugins/github-repo-scaffolding-golang_plugin.md
- docs/plugins/githubactions-golang_plugin.md
- docs/plugins/githubactions-nodejs_plugin.md
- docs/plugins/githubactions-python_plugin.md
- docs/plugins/jira-github-integ_plugin.md
- docs/plugins/trello-github-integ_plugin.md
📖: adding the description of the `tokens setting method`
Thanks to @warren830 , he found it's hard to start testing the `trello-github-integ` plugin, so I realized that the documentation needs to be supplemented.
> 📖: adding the description of the `tokens setting method`

- Makefile
- build/package/build_linux_amd64.sh
- cmd/trello/main.go
- docs/plugins/trello_plugin.md
- internal/pkg/plugin/trello/create.go
- internal/pkg/plugin/trello/delete.go
- internal/pkg/plugin/trello/helper.go
- internal/pkg/plugin/trello/read.go
- internal/pkg/plugin/trello/trello.go
- internal/pkg/plugin/trello/update.go
- internal/pkg/plugin/trello/validation.go
1.  separate plug-in for create Trello board, add outputs
separate plug-in for create Trello board, add outputs
#314
> feat: separate plug-in for create Trello board

- hack/terraform/config.tf
- hack/terraform/devstream-iam.tf
- hack/terraform/main.tf
- Terraform EKS update to deploy AWS EKS as e2e test env
- IAM update to create users for the team
> feat: terraform eks/iam update

- .gitignore
- docs/Makefile
- docs/architecture.md
- docs/conf.py
- docs/core_concept.md
- docs/creating_a_plugin.md
- docs/development_workflow.md
- docs/index.md
- docs/overview.md
- docs/project_layout.md
- docs/quickstart_en.md
- docs/roadmap.md
Renamed a few docs; testing for readthedocs.io.
> Docs: support readthedocs.io

- internal/pkg/pluginengine/change.go
- internal/pkg/pluginengine/cmd_apply.go
- pkg/util/log/log.go
> fix: trello logs improvement

- docs/best_practices/gitops.md
- docs/plugins/argocdapp_plugin.md
- examples/gitops.yaml
Adding dependency logic in gitops.md
- `config-gitops.yaml`
```sh
tools:
- name: go-webapp-repo
plugin:
kind: github-repo-scaffolding-golang
version: 0.2.0
options:
owner: daniel-hutao
repo: go-webapp
branch: main
image_repo: exploitht/go-webapp
- name: jira-github-default
plugin:
kind: jira-github-integ
version: 0.2.0
dependsOn: [ "go-webapp-repo.github-repo-scaffolding-golang" ]
options:
owner: daniel-hutao
repo: go-webapp
jiraBaseUrl: https://JIRA_ID.atlassian.net
jiraUserEmail: tao.hu@merico.dev
jiraProjectKey: DT
branch: main
- name: golang-webapp-actions
plugin:
kind: githubactions-golang
version: 0.2.0
dependsOn: [ "go-webapp-repo.github-repo-scaffolding-golang" ]
options:
owner: daniel-hutao
repo: go-webapp
language:
name: go
version: …
```
> docs(gitops): adding dependency logic in gitops.md

- docs/index.md
- docs/output.md
A new, simple doc for our recent "output" feature.
> docs: add output documentation

- internal/pkg/develop/plugin/template/update.go
> fix(develop template): fix update_go_nameTpl

- .gitignore
- internal/pkg/develop/plugin/template/NAME_plugin.md.go
changed docs/plugins/plugin/ to docs/plugins/
added README_when_create_plugin.md to .gitignore
> fix(develop template): fix NAME_plugin_md_dirTpl

- README.md
main-builder.yaml -> main-pushed.yml at README.md
> fix: main-builder.yaml -> main-pushed.yml at README.md

- internal/pkg/develop/plugin/template/create.go
- internal/pkg/develop/plugin/template/delete.go
- internal/pkg/develop/plugin/template/read.go
- internal/pkg/develop/plugin/template/update.go
adding more common logic in template
/cc @imxw @warren830 @summingyu
> feat(develop/create-plugin): adding more common logic in template

- .github/workflows/e2e-test.yml
- .github/workflows/main-pushed.yml
- .github/workflows/pr-created.yml
- Makefile
- README.md
- test/e2e/yaml/e2e-config.yaml
See the link below for more info:
https://github.com/daniel-hutao/stream/runs/5677470780?check_suite_focus=true
> ci: e2e-test from `actions` to `eks`

- .gitignore
Note: please complete **_ALL_** items in the following checklist, and **_remove this section before submitting_**.
- I have read through the [CONTRIBUTING.md](../CONTRIBUTING.md) documentation.
- This PR is using a `label` (bug, feature, etc.)
- My code has the necessary comments and documentation (if needed).
- I have added relevant tests
- I will remove this section (**⚠️ Pre-Checklist**) when submitting this PR
I use VSCode for programming and I want Git to ignore VSCode-specific files in `.vscode`.
n/a
n/a
n/a
n/a
n/a
> chore: update .gitignore to ignore .vscode directory

- Makefile
- internal/pkg/plugin/githubactions/python/create.go
- internal/pkg/plugin/githubactions/python/delete.go
- internal/pkg/plugin/githubactions/python/read.go
- internal/pkg/plugin/githubactions/python/update.go
- internal/pkg/plugin/githubactions/python/validate.go
- internal/pkg/plugin/jiragithub/create.go
- internal/pkg/plugin/jiragithub/delete.go
- internal/pkg/plugin/jiragithub/helper.go
- internal/pkg/plugin/jiragithub/read.go
- internal/pkg/plugin/jiragithub/update.go
1. jiragithub
2. githubactions-python
reduce the repeated execution of commands
> Refactor: be consistent with the plugin template

- .github/workflows/automated-release.yml
- .github/workflows/e2e-test.yml
fix: install goimports at e2t-test workflow job
> fix: install goimports at e2t-test workflow job

- internal/pkg/pluginmanager/manager.go
should be if... else return err
> fix: fix the return error

- docs/development_workflow.md
docs: update stream to devstream
> docs: update stream to devstream

- docs/output.md
> docs: change `demo` to `repo`

- Makefile
- build/package/auto-release-darwin-arm64.sh
- build/package/upload_assets.sh
- cmd/devstream/init.go
- internal/pkg/pluginmanager/manager.go
remove dtm md5 validation and uploading .md5 file
keep plugins' md5 validation
#388
> feat: remove dtm md5 validation and uploading .md5 file

- internal/pkg/show/config/config.go
- internal/pkg/show/config/plugin/argocdapp.go
- internal/pkg/show/config/plugin/devlake.go
- internal/pkg/show/config/plugin/github-repo-scaffolding-golang.go
- internal/pkg/show/config/plugin/githubactions-golang.go
- internal/pkg/show/config/plugin/githubactions-nodejs.go
- internal/pkg/show/config/plugin/githubactions-python.go
- internal/pkg/show/config/plugin/gitlabci-golang.go
Support default config print logic
#383 
N/A
N/A
N/A
N/A
> Feat: support default config print logic

- .github/workflows/e2e-test.yml
- docs/best_practices/gitops.md
- docs/plugins/argocdapp.md
- docs/plugins/github-repo-scaffolding-golang.md
- docs/plugins/githubactions-golang.md
- docs/plugins/githubactions-nodejs.md
- docs/plugins/githubactions-python.md
- examples/gitops.yaml
- internal/pkg/show/config/plugin/argocdapp.go
- internal/pkg/show/config/plugin/github-repo-scaffolding-golang.go
- internal/pkg/show/config/plugin/githubactions-golang.go
- internal/pkg/show/config/plugin/githubactions-nodejs.go
- internal/pkg/show/config/plugin/githubactions-python.go
- pkg/util/github/github_test.go
- test/e2e/yaml/e2e-config.yaml
Feat: decuple the dtm with personal account
> Feat: decuple the dtm with personal account

- ROADMAP.md
> docs: update roadmap with more plugins

- .github/workflows/e2e-test.yml
- docs/config.md
- docs/index.md
- test/e2e/yaml/e2e-config.yaml
- test/e2e/yaml/e2e-variables.yaml
- add variables into e2e test
- add a new doc on config/dependency/variables
> docs/tests: add docs and e2e tests for variables

- Makefile
- build/package/auto-release-darwin-arm64.sh
- docs/conf.py
> release: v0.4.0

- .github/workflows/automated-release.yml
- build/package/upload_assets.sh
fix: devstream repo/user name error
> fix: devstream repo/user name error

- build/package/auto-release-darwin-arm64.sh
auto-release-darwin-arm64.sh should check all variables. If empty, no error should occur.
#427
> fix: validate params

- examples/gitops.yaml
- internal/pkg/plugin/githubactions/golang/create.go
- internal/pkg/plugin/githubactions/golang/jobs.go
- internal/pkg/plugin/githubactions/golang/render.go
- internal/pkg/plugin/githubactions/golang/templates.go
- internal/pkg/pluginengine/change.go
- internal/pkg/pluginengine/change_helper.go
- internal/pkg/pluginengine/cmd_apply.go
- internal/pkg/pluginengine/topological_sort.go
- internal/pkg/show/config/plugin/githubactions-golang.go
- internal/pkg/statemanager/manager.go
- test/e2e/yaml/e2e-config.yaml
some bugfix and logs improvement
Close #432 
Close #434 
https://github.com/devstream-io/website/pull/14
---
> Bug: some bugfix and logs improvement

- cmd/plugin/gitlab-repo-scaffolding-golang/main.go
- internal/pkg/plugin/common/reposcaffolding/options.go
- internal/pkg/plugin/reposcaffolding/gitlab/golang/create.go
- internal/pkg/plugin/reposcaffolding/gitlab/golang/delete.go
- internal/pkg/plugin/reposcaffolding/gitlab/golang/golang.go
- internal/pkg/plugin/reposcaffolding/gitlab/golang/read.go
- internal/pkg/plugin/reposcaffolding/gitlab/golang/update.go
- internal/pkg/show/config/config.go
- internal/pkg/show/config/plugin/gitlab-repo-scaffolding-golang.go
- pkg/util/gitlab/commits.go
- pkg/util/gitlab/project.go
GitLab repository bootstrapping plugin (for Golang webapp).
Also, some more functions in the gitlab pkg (mostly commit and project related) are created.
See: https://github.com/devstream-io/website/pull/20
> Feat gitlab golang scaffolding plugin

- cmd/devstream/develop.go
- internal/pkg/develop/plugin/plugin.go
- internal/pkg/show/status/status.go
chore: log format improvement with validate-plugin
#441
> chore: log format improvement with validate-plugin

- README.md
- docs/README_zh.md
Some small visual optimizations with the readme file.
/cc @IronCore864
> chore: some small visual optimizations with the readme file

- docs/README_zh.md
Adding slack link in the README_zh.md
/cc @IronCore864
> chore: adding slack link in the README_zh.md

- build/package/auto-release-darwin-arm64.sh
chore: udpate the release version
> chore: udpate the release version

- examples/gitops.yaml
- examples/quickstart.yaml
update  annotation in the config files
> fix: update comments

- .github/workflows/e2e-test.yml
- test/e2e/yaml/e2e-config.yaml
- test/e2e/yaml/e2e-tools.yaml
fix e2e failed error after config file updated.
New error:
> fix: e2e failed when config file updated

- docs/index.md
- mkdocs.yml
- add a temporary default doc
- fix github link
> docs: add default doc

- docs/tutorials/best-practices/gitops.md
- internal/pkg/show/status/status.go
- gitops.md missing DOCKERHUB_TOKEN setting
- log improvement with `dtm show status`
- default instance name logic with `dtm show status`
> Fix: some log improvement & bugfix

- internal/pkg/configloader/config.go
- internal/pkg/configloader/validation.go
- internal/pkg/configloader/variables.go
fix file validation
- varfile not null validation
- toolfile not null validation
- state not null validation
> fix: fix file validation

- internal/pkg/show/config/config.go
- internal/pkg/show/config/defaultconfig.go
Complete the proposal #468 
#468
> feat: command `dtm show config` with no flag to print main config sample

- internal/pkg/pluginengine/cmd_destroy.go
bugfix & logs improvement
Describe tool instances information before exec destroy command
https://github.com/devstream-io/devstream/issues/429
```shell
$ ./dtm destroy
2022-04-21 23:05:48 ℹ [INFO]  Destroy started.
2022-04-21 23:05:50 ℹ [INFO]  Start executing the plan.
2022-04-21 23:05:50 ℹ [INFO]  Changes count: 1.
2022-04-21 23:05:50 ℹ [INFO]  -------------------- [  Processing progress: 1/1.  ] --------------------
2022-04-21 23:05:50 ℹ [INFO]  Processing: vault (vault) -> Delete ...
2022-04-21 23:05:51 ℹ [INFO]  Uninstalling openldap helm chart.
2022-04-21 23:05:51 ⚠ [WARN]  Release is not found, maybe it has been deleted.
```
```shell
ubuntu@VM-12-5-ubuntu:~/dtmtest$ ./dtm destroy -f config.yaml
2022-05-13 10:21:33 ℹ [INFO]  Destroy …
```
> fix: add tool instances information before destroy

- docs/index.md
docs: adding community link & fix blog link
> docs: adding community link & fix blog link

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/documentation.yaml
- .github/ISSUE_TEMPLATE/proposal.yaml
Fix the issue templates syntax error
> fix: issue templates syntax error

- CONTRIBUTING.md
- README.md
docs: fix some links error
N/A
> 📖 `Docs`: fix some links error

- cmd/devstream/develop.go
> fmt: remove unused dependencies

- internal/pkg/configloader/config.go
- internal/pkg/configloader/validation.go
1. fix the panic error;2. 
2. set the state file to `devstream.state` when it's empty;
fix #563 
I've tested it locally, everything are ok!
> fix: config file render failed

- .github/workflows/automated-release.yml
- internal/pkg/statemanager/manager.go
fix: upload_assets.sh path error
> fix: upload_assets.sh path error

- .github/workflows/automated-release.yml
- internal/pkg/statemanager/manager.go
During the release process, we commit the bugfix directly to the release branch. When v0.6.0 is released, we will merge these bugfixes back to the main
> Merge release-0.6 to main branch

- docs/quickstart_en.md
- docs/quickstart_zh.md
Now I use absolute paths for links.
> fix: docs 404 links

- .github/workflows/automated-release.yml
- Makefile
- hack/release/auto-release-darwin-arm64.sh
> chore: update release version related bug

- internal/pkg/configloader/config.go
- internal/pkg/configloader/variables.go
> fix(configloader): add missing judgement

- Makefile
> fix:gopath is no longer set

- README.md
- docs/README_zh.md
- docs/best-practices/gitops.md
Readme and GitOps best practice docs update with v0.6.0 demo video links.
> docs: add demo video links

- docs/assets/versions.css
- docs/assets/versions.js
- docs/versions.json
- mkdocs.yml
> Docs add versions

- docs/quickstart_en.md
- docs/quickstart_zh.md
- examples/quickstart.yaml
- examples/tools-quickstart.yaml
Update v0.6 quickstart docs according to config file refactor.
> docs: update quickstart for varFile

- internal/pkg/plugin/reposcaffolding/github/golang/golang.go
- internal/pkg/pluginengine/change.go
- internal/pkg/pluginengine/cmd_apply.go
- internal/pkg/pluginengine/cmd_delete.go
- internal/pkg/pluginengine/cmd_destroy.go
- pkg/util/github/branch.go
- pkg/util/github/pullrequest.go
- pkg/util/github/repo.go
- bug fix: changes count now displays correctly
- bug fix: delete/destroy changes order now is fixed
- fix: repo scaffolding now can pass successfully
- create repo with a default branch (main)
- initialize the branch first before creating commits
- delete the branch after PR is merged
- improvement: add necessary logging and comments
Closes https://github.com/devstream-io/devstream/issues/622
> Fix repo scaffolding empty main branch

- ROADMAP.md
> docs: update roadmap with issues

- docs/best-practices/gitops.md
- docs/plugins/argocd.md
- docs/plugins/argocdapp.md
- docs/plugins/devlake.md
- docs/plugins/github-repo-scaffolding-golang.md
- docs/plugins/githubactions-golang.md
- docs/plugins/githubactions-nodejs.md
- docs/plugins/githubactions-python.md
- docs/plugins/gitlab-repo-scaffolding-golang.md
- docs/plugins/gitlabci-generic.md
- docs/plugins/gitlabci-golang.md
- docs/plugins/hashicorp-vault.md
- docs/plugins/jenkins.md
- docs/plugins/jira-github-integ.md
- docs/plugins/kube-prometheus.md
- docs/plugins/openldap.md
- docs/plugins/trello-github-integ.md
- docs/plugins/trello.md
- internal/pkg/develop/plugin/template/NAME_plugin.md.go
- mkdocs.yml
- Embed yaml file in plugin md file, so that developers only need to maintain `plugin_name.yaml` file
- `dtm develop create-plugin -p xxx` automatically integrates `plugin_name.yaml` in `plugin_name.md`
- Support site dark mode
- Embed youtube & bilibili videos in https://docs.devstream.io/en/latest/best-practices/gitops/
- Support code highlight
- Support showing code block title with the programming language name
- Enable doc editing mode
#652
> docs: optimize document display

- CODEOWNERS
> chore: add code owners file

- docs/commands/destroy.md
- docs/commands/develop.md
- docs/commands/init.md
- docs/commands/verify.md
- docs/contribute.md
- docs/core-concepts/config.md
- docs/core-concepts/output.md
- docs/core-concepts/variables.md
- docs/development/architecture.md
- docs/index.md
- docs/quickstart_en.md
- docs/quickstart_zh.md
Please see #656 for more information.
close #656
> docs: fix some link errors

- internal/pkg/configloader/coreconfig.go
> feat: CoreConfig varFile and toolFile Relative Path Support

- internal/pkg/configloader/coreconfig.go
chore: fix some log error about pr622
> chore: fix some log error about pr622

- pkg/util/downloader/downloader.go
- pkg/util/downloader/downloader_test.go
1. improve coverage
2. Optimize return time in case of errors
> test(downloader): add downloader test case

- cmd/devstream/apply.go
- cmd/devstream/main.go
- Fix duplicate error output
- Suggestion for  `dtm install`
#667 
```go
✅ 😁 dtm install
Error: unknown command "install" for "dtm"
Run 'dtm --help' for usage.
2022-06-11 14:52:25 ✖ [FATAL]  Did you mean "dtm apply" instead?
```
> fix: duplicate error output

- .github/pull_request_template.md
- docs/best-practices/gitops.md
- docs/commands/init.md
- docs/commands/verify.md
- docs/contribute.md
- docs/core-concepts/config.md
- docs/core-concepts/output.md
- docs/core-concepts/variables.md
- docs/development/architecture.md
- docs/development/creating-a-plugin.md
- docs/plugins/argocdapp.md
- docs/quickstart_en.md
- docs/quickstart_zh.md
- docs/understanding_the_basics.md
1. add md suffix and relative position for link
2.  modified CONTRIBUTING 's link in pull_request_template.md
none
click link in github doc, would never 404
click link in https://www.devstream.io/ would never 404
> docs: fix some link errors 

- mkdocs.yml
> docs: add HOME link

- docs/index.zh.md
Replace Youtube with BiliBili
close #685
> feat: complete chinese of index

- docs/development/test.md
add usage doc for local-e2e-test script
#664
> docs: add usage for local-e2e-test script

- internal/pkg/configloader/toolconfig.go
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
Resolved #558
None
> refactor: use validator for configloader validation

- docs/development/commit-messages.zh.md
Signed-off-by: aucker <aucker@qq.com>
This PR translate the docs `commit-messages.md` into Chinese.
This PR is related to this [issue](https://github.com/devstream-io/devstream/issues/709)
Closes https://github.com/devstream-io/devstream/issues/709.
The Chinese version of `commit-messages.md`.
> Docs(Translation): Commit Messages - Chinese Version #709

- internal/pkg/pluginmanager/manager.go
Signed-off-by: zhaozhenhang zhaozhenhang@kuaishou.com
close #654
> fix(pluginmanager): resolve dtm init prompt error during first download

- docs/quickstart_en.md
- docs/quickstart_zh.md
- examples/variables-quickstart.yaml
> docs: fix config yaml 404

- docs/best-practices/gitops.md
- docs/best-practices/gitops.zh.md
- docs/development/commit-messages.zh.md
Translate the GitOps.md into Chinese.
Minor fix in commit-messages.zh.md file.
This PR is related to #715 #720 
This PR is the refinement version of #720 with DCO and some review.
> docs(translation): GitOps Toolchain - Chinese Version #715

- internal/pkg/plugin/gitlabcedocker/create.go
- internal/pkg/plugin/gitlabcedocker/delete.go
- internal/pkg/plugin/gitlabcedocker/gitlabcedocker.go
- internal/pkg/plugin/gitlabcedocker/sshoperator.go
> feat(gitlab-ce-docker): separate image name and tag in gitlab-ce-docker plugin

- docs/best-practices/gitops.md
- docs/quickstart_en.md
- docs/quickstart_zh.md
> docs: fix links errors and minor changes

- docs/best-practices/gitops.md
> docs: fix punctuation errors

- docs/best-practices/gitops.md
- docs/best-practices/gitops.zh.md
- docs/quickstart.md
- docs/quickstart.zh.md
Update docs sample config YAML URL for release 0.7.
> docs: update sample config yaml url for v0.7

- docs/assets/versions.js
Change version js file to add a notice msg for non-stable versions of doc.
> docs: update notice msg for non-stable version docs

- docs/development/development-workflow.zh.md
> Docs: translate development-workflow into Chinese

- internal/pkg/develop/plugin/template/NAME_plugin.zh.md.go
Signed-off-by: chengdehao <dehaocheng@kubesphere.io>
fix https://github.com/devstream-io/devstream/issues/694
> feat:supports automatic scaffolding of the PLUGIN_NAME.zh.md file

- internal/pkg/plugin/gitlabcedocker/create.go
- internal/pkg/plugin/gitlabcedocker/delete.go
- internal/pkg/plugin/gitlabcedocker/gitlabcedocker.go
- internal/pkg/plugin/gitlabcedocker/options.go
- internal/pkg/plugin/gitlabcedocker/sshoperator.go
- internal/pkg/show/config/plugins/gitlab-ce-docker.yaml
Signed-off-by: amdaous <dreamlife1991@163.com>
export image tag var
#734
> chore: export image tag var

- README.md
- docs/README_zh.md
> docs: fix broken links in readme en/zh

- hack/e2e/e2e-up.sh
> fix: fix arch error in e2e-up.sh

- .github/ISSUE_TEMPLATE/config.yml
- README.md
- docs/README_zh.md
- docs/contributing_guide.md
- docs/contributing_guide.zh.md
- docs/development/good-first-issues.md
- docs/development/good-first-issues.zh.md
Embedding 'openssl best practices' in the README files.
See https://bestpractices.coreinfrastructure.org/en for more info.
> docs: embedding 'openssl best practices' in the README files

- docs/quickstart.zh.md
> fix(d0c): fix link error in quickstart

- docs/commands/apply.md
- docs/development/project-layout.md
- docs/development/project-layout.zh.md
- docs/plugins/argocdapp.md
- docs/plugins/openldap.md
Signed-off-by: BSS ZU <274620705z@gmail.com>
This PR translate the docs project-layout.zh.md into Chinese.
close #711
> docs: update project-layout.zh.md

- GOVERNANCE.md
- mkdocs.yml
> docs: add governance doc

- docs/core-concepts/variables.md
Signed-off-by: cezhang <c1zhang.dev@gmail.com>
> docs: typo

- docs/core-concepts/config.zh.md
Signed-off-by: 高强 <qiang.gao@yeepay.com>
> docs: update config.zh.md

- .github/workflows/e2e-test.yml
- [] I have added relevant tests
If e2e actions fail,  alarm to  feishu
alarm like this:
> feat: e2e alert to feishu if e2e actions failure

- .github/workflows/e2e-test.yml
> Feat e2e alert feishu

- .github/workflows/link-pr.yml
- .github/workflows/link.yml
speed up links CI.
**33s -> 9s**
close #811
> feat: speed up `links` CI

- README.md
- docs/README_zh.md
> docs: update slack info in readme

- internal/pkg/show/config/config.go
- internal/pkg/show/config/embed_gen.go
- internal/pkg/show/config/gen_embed_var.go
- internal/pkg/show/config/gitops.yaml
Signed-off-by: karasart <1074754763@qq.com>
add CLI command "dtm show config --template=gitops" to show gitops.yaml
#598
> feat: add CLI command "dtm show config --template=gitops" to show gitops.yaml

- cmd/devstream/init.go
- internal/pkg/configloader/config.go
- internal/pkg/pluginmanager/manager.go
- internal/pkg/version/version.go
1. fix duplicate downloads logic
2. make outputs more beautiful
3. refactor some code
close #818 
The version in 3 screenshots is a forced change during testing, and the commits have been submitted in accordance with the normal.
> Fix duplicate downloads and refactor code

- .github/workflows/e2e-test.yml
- .github/workflows/main.yml
when main build actions or e2e actions failure, send a message to feishu group on failure and include the url o…
https://github.com/devstream-io/devstream/issues/636
> feat: send a message to feishu group on actions failure and include the url of actions

- internal/pkg/pluginmanager/downloader.go
- internal/pkg/pluginmanager/downloader_test.go
mock download logic in unit test
#827
> feat: mock download test logic in pluginmanager

- .github/ISSUE_TEMPLATE/bug-report.yaml
update the version info in the bug-report.yaml
N/A
The version switch changed from 0.6.0 to 0.7.0 when bug reporting
> chore: update the version info in the bug-report.yaml

- cmd/plugin/harbor/main.go
- docs/plugins/harbor.md
- docs/plugins/harbor.zh.md
- internal/pkg/plugin/harbor/create.go
- internal/pkg/plugin/harbor/delete.go
- internal/pkg/plugin/harbor/harbor.go
- internal/pkg/plugin/harbor/read.go
- internal/pkg/plugin/harbor/state.go
- internal/pkg/plugin/harbor/update.go
- internal/pkg/plugin/harbor/validate.go
- internal/pkg/show/config/embed_gen.go
- internal/pkg/show/config/plugins/harbor.yaml
This plugin install harbor in a existing kubernetes environment by helm
#607 
1. Edit config file to use harbor plugin
2. Run `dtm apply -y`, this plugin will be installed
3.  Now harbor is up and can be visited
> feat: new plugin harbor #607

- docs/core-concepts/core-concepts.zh.md
> Docs: add new translated blog - Tool, State, and Resource - Chinese Version

- docs/quickstart.md
- docs/quickstart.zh.md
Do you have more suggestions on typography and line breaks?
close #883
> docs: improve github token part

- pkg/util/github/branch_test.go
- pkg/util/github/commit_test.go
- pkg/util/github/file_test.go
- pkg/util/github/github_test.go
- pkg/util/github/release_test.go
add ut for commit and file
```sh
[going@dev github]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/github/branch.go:11:                 NewBranch                               100.0%
github.com/devstream-io/devstream/pkg/util/github/branch.go:38:                 DeleteBranch                            100.0%
github.com/devstream-io/devstream/pkg/util/github/commit.go:11:                 GetLastCommit                           100.0%
github.com/devstream-io/devstream/pkg/util/github/download.go:14:               DownloadAsset                           0.0%
github.com/devstream-io/devstream/pkg/util/github/download.go:83: …
```
> Feat: pkg/util/gitHub/commit&file enhancement

- internal/pkg/plugin/artifactory/artifactory.go
- internal/pkg/plugin/artifactory/create.go
- internal/pkg/plugin/artifactory/update.go
Fix the helm plugin error for getting state.
#896
> fix: artifactory plugin error for state get

- pkg/util/github/pullrequest_test.go
- test/e2e/yaml/e2e-tools.yaml
Fix e2e error because of indent and square brackets
> fix: e2e test error because of indent and square brackets

- test/e2e/yaml/e2e-tools.yaml
> fix: add missing  brackets

- .github/workflows/update-fig-spec.yml
Signed-off-by: xuwu <ixw1991@126.com>
- Generate  fig auto-complete spec and make a pr to [withfig/autocomplete](https://github.com/withfig/autocomplete) automatically
- **Create a personal access  token which has `repo` scope permission**
- **Add the above token's value to [devstream-io/devstream](https://github.com/devstream-io/devstream) as a repo secret and name it as `FIG_TOKEN`**
close #627
> ci: add update fig spec workflow

- pkg/util/github/coverage.html
- pkg/util/github/workflow.go
- pkg/util/github/workflow_helper.go
- pkg/util/github/workflow_helper_test.go
- pkg/util/github/workflow_test.go
add ut for workflow
```sh
github.com/devstream-io/devstream/pkg/util/github/workflow.go:23:               AddWorkflow                             100.0%
github.com/devstream-io/devstream/pkg/util/github/workflow.go:60:               DeleteWorkflow                          100.0%
github.com/devstream-io/devstream/pkg/util/github/workflow.go:102:              VerifyWorkflows                         97.0%
github.com/devstream-io/devstream/pkg/util/github/workflow.go:162:              GetWorkflowPath                         100.0%
github.com/devstream-io/devstream/pkg/util/github/workflow.go:187: …
```
> feat: pkg-util-github-workflow enchancement

- .github/workflows/e2e-test.yml
limit the number of concurrent actions to 1, do not cancel running actions
> ci: limit the number of concurrent actions to 1, do not cancel running actions

- docs/plugins/artifactory.md
- docs/plugins/artifactory.zh.md
- docs/plugins/harbor.md
- docs/plugins/harbor.zh.md
- internal/pkg/plugininstaller/helm/installer.go
Repair harbor/artifactory doc error for test locally
cloase #945, #944, #942
> Bugfix plugin error

- docs/plugins/artifactory.md
- docs/plugins/artifactory.zh.md
Co-author: Daniel Hu <tao.hu@merico.dev>
Transferring the work of #943 to resolve conflicts.
> docs: fix artifactory plugin doc format error

- docs/plugins/gitlabci-java.md
- docs/plugins/gitlabci-java.zh.md
- docs/plugins/jenkins-github-integ.md
- docs/plugins/jenkins-github-integ.zh.md
- docs/plugins/jenkins-pipeline-kubernetes.md
- docs/plugins/jenkins-pipeline-kubernetes.zh.md
- docs/plugins/tekton.md
- docs/plugins/tekton.zh.md
- internal/pkg/develop/plugin/template/NAME_plugin.md.go
- internal/pkg/develop/plugin/template/NAME_plugin.zh.md.go
> docs: fix link error in tekton

- hack/quick-start/quickstart.sh
Add token to avoid  github api rate limit
#955 
Signed-off-by: csonezp <csonezp@gmail.com>
> fix: add token to avoid  github api rate limit

- Makefile
Signed-off-by: Zhenyuan Lau <zhenyuanlau@outlook.com>
```bash
➜  devstream git:(main) make lint
```
got:
```bash
Run golangci to lint source codes
make: golangci-lint: No such file or directory
make: *** [lint] Error 1
```
```bash
➜  devstream git:(fix-make-lint) make lint
```
got
```bash
Run golangci to lint source codes
```
> fix: make lint error

- .golangci.yml
enlarge goglangci-lint timeout to 10mins for github actions timeout error
> improvement golangci lint for github actions timeout error

- internal/pkg/plugininstaller/kubectl/installer.go
- internal/pkg/plugininstaller/kubectl/installer_test.go
- internal/pkg/plugininstaller/kubectl/kubectl_suite_test.go
ut for installer
N/A
Ran 5 of 5 Specs in 0.496 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestKubectl (0.51s)
PASS
coverage: 91.7% of statements
ok      github.com/devstream-io/devstream/internal/pkg/plugininstaller/kubectl  0.523s
> feat: internal-pkg-plugininstaller-kubectl-installer enhancement

- internal/pkg/plugininstaller/kubectl/installer.go
- internal/pkg/plugininstaller/kubectl/installer_test.go
> fix: forget to render kubectl options

- pkg/util/template/getter_test.go
- pkg/util/template/render_test.go
- pkg/util/template/renderer_test.go
- pkg/util/template/template_suite_test.go
> test: complete uts in pkg `pkg/utl/template`

- .lycheeignore
- docs/plugins/harbor.zh.md
Refine the harbor plugin documentation
N/A
N/A
> Docs: Refine the harbor Plugin Documentation

- docs/plugins/harbor.zh.md
Refile the document with `harbor` plugin
#993
N/A
> Docs: Refine the Document with harbor Plugin

- test/e2e/yaml/e2e-config.yaml
> fix: e2e plugin dir

- internal/pkg/plugin/jenkins/jenkins.go
jenkins plugin jenkins_url improvement
https://github.com/devstream-io/devstream/pull/1025#discussion_r952277174
N/A
> feat: jenkins Plugin jenkins_url Improvement

- .github/workflows/automated-release.yml
- Makefile
- hack/release/auto-release-darwin-arm64.sh
- hack/release/upload_assets.sh
- test/e2e/yaml/e2e-config.yaml
> chore: update default plugins dir in makefile/ci/test

- internal/pkg/plugin/githubactions/golang/main.tpl.yml
> fix: golang githubactions tempalte syntax error

- Makefile
- internal/pkg/show/config/default.yaml
- test/e2e/yaml/e2e-config.yaml
https://github.com/aFlyBird0/devstream/runs/8129056745?check_suite_focus=true
> test: fix plugin dir error

- internal/pkg/plugin/jenkinspipeline/create.go
- internal/pkg/plugininstaller/ci/installer.go
- internal/pkg/plugininstaller/ci/option.go
- internal/pkg/plugininstaller/jenkins/option.go
- internal/pkg/plugininstaller/jenkins/option_test.go
- internal/pkg/plugininstaller/jenkins/state.go
- internal/pkg/plugininstaller/jenkins/validate.go
- internal/pkg/plugininstaller/jenkins/validate_test.go
- internal/pkg/show/config/plugins/jenkins-pipeline.yaml
plugin jenkins-pipeline config options refactoring. see #1055 for more info
close #1055
test:
- config
```yaml
---
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
backend: local
options:
---
tools:
- name: jenkins-pipeline
dependsOn: []
options:
jenkins:
url: http://54.71.232.26:32000
user: admin
namespace: jenkins
enableRestart: true
scm:
projectURL: http://54.71.232.26:30080/root/spring-demo
projectBranch: master
pipeline:
jobName: test-job
jenkinsfilePath: https://raw.githubusercontent.com/devstream-io/dtm-jenkins-pipeline-ex …
```
> Refactor: plugin jenkins-pipeline Config Options Refactoring

- docs/core-concepts/config.md
- docs/core-concepts/config.zh.md
- docs/core-concepts/dependencies.md
- docs/core-concepts/output.md
- docs/plugins/argocdapp.md
- docs/plugins/ci-generic.md
- docs/plugins/ci-generic.zh.md
- docs/plugins/repo-scaffolding.md
- docs/plugins/repo-scaffolding.zh.md
- examples/gitops.yaml
- examples/quickstart.yaml
- internal/pkg/plugininstaller/ci/validate_test.go
- internal/pkg/plugininstaller/common/repo.go
- internal/pkg/plugininstaller/reposcaffolding/option.go
- internal/pkg/show/config/default.yaml
- internal/pkg/show/config/plugins/gitlabci-generic.yaml
- internal/pkg/show/config/plugins/gitlabci-golang.yaml
- internal/pkg/show/config/plugins/repo-scaffolding.yaml
- internal/pkg/show/config/templates/gitops.yaml
- internal/pkg/show/config/templates/quickstart.yaml
- test/e2e/yaml/e2e-test-local.yaml
- test/e2e/yaml/e2e-tools.yaml
Plugin repo-scaffolding options style fixed
N/A
N/A
> fix: plugin repo-scaffolding options style fixed

- pkg/util/scm/gitlab/repo.go
- pkg/util/scm/gitlab/repo_test.go
- close `Gitlab` `AutoDevops` config
#993
> feat: close gitlab autodevops option

- hack/quick-start/quickstart.sh
Download quickstart.yaml from latest release branch rather than main branch.
fix #1072
> fix: download quickstart.yaml from latest release branch

- internal/pkg/plugininstaller/common/state.go
- pkg/util/helm/helm.go
- pkg/util/helm/helm_operation_test.go
- pkg/util/helm/helm_test.go
- pkg/util/helm/state.go
- pkg/util/helm/state_test.go
- pkg/util/helm/validation.go
- pkg/util/helm/validation_test.go
Fixed: https://github.com/devstream-io/devstream/issues/1075
> feat: Optimize helm pkg

- .lycheeignore
ignore ip url in link checker
N/A
ignore ip url in link checker
> Feat: Ignore IP URL in Link Checker

- .github/ISSUE_TEMPLATE/bug-report.yaml
- Makefile
1. update bug-report template to v0.9.0
2. fix Makefile error -> dtm-xxx-xxx is used by auto-release script
N/A
> Fix: CI Template Updated and Makefile Updated

- docs/best-practices/gitlab-jenkins-harbor.zh.md
document updated: jenkins installation failed with plugins dependencies error
N/A
> Docs: Jenkins Installation Failed with Plugins Dependencies Error

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/workflows/automated-release.yml
- Makefile
- docs/best-practices/gitlab-jenkins-harbor.zh.md
- docs/plugins/jenkins.zh.md
Please merge this pr after v0.9.0 be released
N/A
bugfix only
> Chore: Update `main` Branch with `release-0.9`

- docs/assets/versions.js
> docs: remove stable version alert

- docs/assets/versions.js
- docs/best-practices/gitlab-jenkins-harbor.zh.md
> Release 0.9

- internal/pkg/plugin/jenkinspipeline/jenkinspipeline.go
- internal/pkg/plugininstaller/jenkins/installer.go
- internal/pkg/plugininstaller/jenkins/option.go
- internal/pkg/plugininstaller/jenkins/option_test.go
- pkg/util/jenkins/jenkins.go
- pkg/util/jenkins/plugins.go
- pkg/util/jenkins/tpl/plugins.tpl.groovy
`Jenkins` plugins support version control
#993
> feat: jenkins plugin support version control

- docs/best-practices/gitlab-jenkins-harbor.zh.md
- docs/best-practices/image-registry.md
- docs/best-practices/image-registry.zh.md
- docs/plugins/harbor.zh.md
- docs/plugins/harbor/harbor-images.txt
- docs/plugins/jenkins.zh.md
- docs/plugins/jenkins/jenkins-images.txt
- hack/image-pull-push.sh
docs: the plugins `harbor` and `jenkins` customize image repository support
#1084
Documents updated only
> Docs: The Plugins `harbor` And `jenkins` Customize Image Repository Support

- docs/plugins/harbor.zh.md
- docs/plugins/jenkins.zh.md
- mkdocs.yml
material for mkdocs enhancement
N/A
N/A
> ci: material for mkdocs enhancement

- hack/release/auto-release-darwin-arm64.sh
> fix: exit when any command fails in auto-release script

- docs/plugins/harbor.zh.md
- docs/plugins/jenkins.zh.md
- docs/plugins/jenkins/jenkins-images.txt
`jenkins` and `harbor` documents enhancement.
1. how to use helm chart locally.
2. how to use customized jenkins image.
3. addd more config templates.
#993
Documents updated only.
> docs: jenkins and harbor documents enhancement

- cmd/devstream/init.go
- docs/commands/init.md
- docs/commands/init.zh.md
> fix: minor errors in `dtm init --download-only`

- .github/ISSUE_TEMPLATE/bug-report.yaml
update bug-report template to version 0.9.1
N/A
N/A
> chore: update bug-report template to version 0.9.1

- cmd/devstream/init.go
> fix: missing return in dtm init

- .github/ISSUE_TEMPLATE/bug-report.yaml
- internal/pkg/configmanager/configmanager.go
fix the log message error
N/A
N/A
> fix: log message error 

- docs/plugins/helm-generic.md
- docs/plugins/helm-generic.zh.md
- docs/plugins/plugins-list.md
Updating the plugin list documentation.
> Docs update plugin list

- go.mod
- internal/pkg/plugin/jenkinspipeline/create.go
- internal/pkg/plugininstaller/jenkins/option.go
- internal/pkg/plugininstaller/jenkins/option_test.go
- internal/pkg/plugininstaller/jenkins/pipeline.go
- internal/pkg/plugininstaller/jenkins/pipeline_test.go
- internal/pkg/plugininstaller/jenkins/plugins.go
- internal/pkg/plugininstaller/jenkins/plugins/dingtalk.go
- internal/pkg/plugininstaller/jenkins/plugins/github.go
- internal/pkg/plugininstaller/jenkins/plugins/gitlab.go
- internal/pkg/plugininstaller/jenkins/plugins/imagerepo.go
- internal/pkg/plugininstaller/jenkins/plugins/sonarqube.go
- internal/pkg/plugininstaller/jenkins/plugins_test.go
- internal/pkg/plugininstaller/jenkins/validate.go
- internal/pkg/show/config/plugins/jenkins-pipeline.yaml
- pkg/util/jenkins/job.go
- pkg/util/jenkins/plugins.go
- pkg/util/jenkins/script.go
- pkg/util/jenkins/tpl/repo-casc.tpl.yaml
- pkg/util/mapz/map.go
- staging/dtm-jenkins-pipeline-example/general/Jenkinsfile
- jenkins-pipeline support dingtalk config
- jenkins-pipeline support sonarqube config
- jenkins-pipeline struct support more plugins
#993  #1086 #639
**dingtalk**
**sonarqube**
> feat: jenkins-pipeline support dingtalk and sonar

- test/e2e/yaml/e2e-tools.yaml
- delete argocd crd after e2e test finished
close #1163
> fix: delete crd after argocd is deleted

- pkg/util/k8s/configmap_test.go
Signed-off-by: Kaitian Xie <kaitian96@outlook.com>
- [n/a] I have added relevant tests
Fix a typo
n/a
n/a
> fix: typo currect -> current

- .github/workflows/e2e-test.yml
install kubectl for self-hosted k8s crd runner
> fix: install kubectl for self-hosted runner fix kubectl not found error

- .github/workflows/link-pr.yml
- .github/workflows/link.yml
fix a problem about link checking on self-runner due to permissions,using github's public actions
> fix: fix a problem about link checking on self-runner due to permission

- internal/pkg/plugininstaller/reposcaffolding/state.go
fix reposcaffolding output error
> fix: reposcaffolding output error

- docs/best-practices/air-gapped-deployment.zh.md
- docs/plugins/helm-installer/harbor.zh.md
- docs/plugins/helm-installer/jenkins.zh.md
> fix: broken links

- README.md
- README_zh.md
resolve https://github.com/devstream-io/devstream/issues/1232
> chore: update root folder links

- docs/pmc.md
- mkdocs.yml
@daniel-hutao @steinliber @aFlyBird0 @KeHaohaoke
I have created a draft of the PMC guide.
Please review.
Feel free to add more details, especially on the "standards" part.
> docs: add pmc guide doc

- internal/pkg/plugin/installer/ci/cifile/server/githubci.go
- internal/pkg/plugin/installer/ci/step/general.go
- internal/pkg/plugin/installer/ci/step/general_test.go
- internal/pkg/plugin/installer/ci/step/language.go
- internal/pkg/plugin/installer/ci/step/language_test.go
- internal/pkg/show/config/plugins/github-actions.yaml
- pkg/util/template/render.go
ci support java/golang/nodejs/python default options
#1253 #1239
> feat: pipeline support language default config

- cmd/plugin/argocdapp/main.go
- cmd/plugin/github-actions/main.go
- cmd/plugin/githubactions-golang/main.go
- cmd/plugin/githubactions-nodejs/main.go
- cmd/plugin/githubactions-python/main.go
- internal/pkg/configmanager/configmanager_test.go
- internal/pkg/configmanager/tool.go
- internal/pkg/configmanager/tool_test.go
- internal/pkg/pluginengine/change.go
Add some uts for configmanager
N/A
N/A
> Test: Add Some UTs for `configmanager` Package

- internal/pkg/configmanager/app.go
- internal/pkg/configmanager/configmanager_test.go
- internal/pkg/configmanager/pipelinetemplate.go
- fix: reposcaffolding source repo auth error
#1239
> fix: reposcaffolding source repo auth error

- internal/pkg/configmanager/pipelineDefault.go
add jenkins-pipeline `jenkins` default options 
#1239
> fix: jenkins add options for config

- .github/workflows/automated-release.yml
install AWS cli with automated-release ci
> fix: automated-realease ci add aws cli

- .github/workflows/automated-release.yml
> Add aws Command in The CI VM

- test/e2e/yaml/e2e-config.yaml
> test: trying to fix e2e

- .github/workflows/e2e-test.yml
- test/e2e/yaml/e2e-config.yaml
> App centric config e2e test

- internal/pkg/pluginengine/outputs.go
- internal/pkg/pluginengine/pluginengine_test.go
- internal/pkg/statemanager/state.go
- fix output render error in normal usage
#1239
> fix: output not render error

- internal/pkg/pluginengine/outputs.go
- pkg/util/jenkins/tpl/seedjob.tpl.groovy
- pkg/util/scm/gitlab/repo.go
- fix branch filter error
#1239
> fix: gitlab webhook branch error

- test/e2e/yaml/e2e-apps.yaml
> test: fix apps e2e

- go.mod
- internal/pkg/plugin/gitlabci/generic/options_test.go
- internal/pkg/plugin/installer/ci/ci_test.go
- internal/pkg/plugin/installer/ci/step/step.go
- internal/pkg/plugin/jenkinspipeline/jenkins.go
- internal/pkg/plugin/jenkinspipeline/option.go
- internal/pkg/plugin/jenkinspipeline/plugins.go
- pkg/util/jenkins/jenkins.go
- pkg/util/jenkins/script.go
- pkg/util/jenkins/tpl/repo-casc.tpl.yaml
- staging/dtm-jenkins-pipeline-example/general/Jenkinsfile
- jenkins status will show in gitlab pipeline
- jenkins support offline config(doesn't install plugin and share library)
#1239
> fix: jenkins support offline and gitlab status

- test/e2e/yaml/e2e-apps.yaml
fix e2e test error for repo config
#1239
> fix: e2e test app repo from owner to org

- .github/workflows/lint-yaml.yml
- .yamllint.yml
- hack/e2e/kind.yaml
- internal/pkg/show/config/plugins/ci-generic.yaml
- internal/pkg/show/config/plugins/gitlabci-java.yaml
> ci: yaml lint

- docs/quickstart.md
- internal/pkg/show/config/templates/quickstart.yaml
> docs: update quickstart

- docs/quickstart.md
- docs/quickstart.zh.md
> docs: translate and beautify quickstart docs

- .github/workflows/e2e-test.yml
- test/e2e/yaml/e2e-apps.yaml
> test: enable debug log for e2e

- docs/best-practices/gitlab-jenkins-harbor.zh.md
- docs/plugins/jenkins-pipeline.zh.md
> fix: typo spring boot

- docs/development/architecture.zh.md
- docs/development/dev/creating-a-plugin.zh.md
> docs: fix typo

- docs/quickstart.md
- docs/quickstart.zh.md
fix quickstart document error
N/A
N/A
> fix: quickstart document error

- docs/best-practices/gitops.md
- docs/best-practices/gitops.zh.md
Update GitOps practice document
N/A
N/A
> Docs: Update GitOps Practice Document

- docs/best-practices/gitlab-jenkins-harbor-java-springboot.zh.md
fix best practice gjh document error
N/A
N/A
> fix: best practice gjh document error

- docs/best-practices/gitops.md
- docs/best-practices/gitops.zh.md
- examples/gitops.yaml
- examples/quickstart.yaml
- internal/pkg/plugin/githubactions/validate.go
- internal/pkg/show/config/templates/gitops.yaml
- internal/pkg/show/config/templates/quickstart.yaml
- pkg/util/scm/git/repoinfo.go
- fix `quickstart.md` and `gitops.md` error 
#1239
> fix: gitops and quickstart error

- internal/pkg/configmanager/pipelineDefault_test.go
- pkg/util/scm/git/repoinfo_test.go
- fix ut error in pr 1353
#1353
> fix: app domain ut error

- docs/best-practices/gitlab-jenkins-harbor-java-springboot.zh.md
fix some document error in best practice "GitLab + Jenkins + Harbor On Premise Toolchain"
N/A
document updated only
> docs: fix some document error in best practice gjh

- .github/ISSUE_TEMPLATE/bug-report.yaml
- hack/release/auto-release-darwin-arm64.sh
release script error fixed.
N/A
bugfixed.
> fix: release script error

- .github/workflows/automated-release.yml
print md5 and commit id in release process
N/A
N/A
> chore: print md5 and commit id in release process

- docs/best-practices/gitlab-jenkins-harbor-java-springboot.zh.md
- docs/index.zh.md
add v0.10.3 demo video
N/A
N/A
> docs: add v0.10.3 demo video

- examples/quickstart.yaml
- internal/pkg/show/config/templates/quickstart.yaml
- fix quickstart ciLocation error
> fix: quickstart ciLocation update to new repo

- staging/dtm-pipeline-templates/gitlab-ci/.gitlab-ci.yml
fix gitlab-ci `APP_NAME` variable lost error
> fix: add appname variable in ci script

- staging/dtm-pipeline-templates/argocdapp/helm/values.yaml
- staging/dtm-pipeline-templates/gitlab-ci/.gitlab-ci.yml
- set image initialTag  to 0.0.1
- helm use 80 port
> fix: gitlab-ci and argocd version error

- staging/dtm-pipeline-templates/argocdapp/helm/templates/deployment.yaml
- staging/dtm-pipeline-templates/argocdapp/helm/values.yaml
- staging/dtm-pipeline-templates/argocdapp/kustomize/guestbook-ui-deployment.yaml
- staging/dtm-pipeline-templates/argocdapp/kustomize/guestbook-ui-svc.yaml
- staging/dtm-repo-scaffolding-golang-gin/Dockerfile.tpl
- staging/dtm-repo-scaffolding-golang-gin/cmd/_app_name_/main.go.tpl
- staging/dtm-repo-scaffolding-python-flask/Dockerfile.tpl
- fix staging repo-scaffolding port permission errror
> fix: all staging default port use above 1024

- docs/development/docs-contribution/mkdocs.zh.md
> fix: doc link error

- pkg/util/helm/helm.go
Set up helm debug mode according to dtm debug mode
N/A
N/A
> chore: set up helm debug mode according to dtm debug mode

- docs/use-cases/gitops-python-flask/1-overview.zh.md
> docs: use cases - gitops-flask-overview - cn

- docs/plugins/helm-installer/argocd.md
- docs/plugins/helm-installer/argocd.zh.md
- docs/plugins/helm-installer/artifactory.md
- docs/plugins/helm-installer/artifactory.zh.md
- docs/plugins/helm-installer/devlake.md
- docs/plugins/helm-installer/devlake.zh.md
- docs/plugins/helm-installer/helm-installer.zh.md
- docs/plugins/helm-installer/kube-prometheus.md
- docs/plugins/helm-installer/kube-prometheus.zh.md
- docs/plugins/helm-installer/openldap.md
- docs/plugins/helm-installer/openldap.zh.md
- docs/plugins/helm-installer/sonarqube.md
- docs/plugins/helm-installer/tekton.md
- docs/plugins/helm-installer/tekton.zh.md
- docs/plugins/helm-installer/vault.md
- docs/plugins/helm-installer/vault.zh.md
- docs/use-cases/helm-installer.md
- docs/use-cases/helm-installer.zh.md
- mkdocs.yml
> docs: use cases - helm installer

- .github/workflows/e2e-test.yml
- docs/use-cases/gitops-python-flask/4-gitlab-dtm-apps.zh.md
- docs/use-cases/gitops/2-gitops-tools.md
- docs/use-cases/gitops/2-gitops-tools.zh.md
> test(e2e): the accessibility of flask

- docs/commands/autocomplete.md
- docs/commands/autocomplete.zh.md
- docs/use-cases/case-overview.zh.md
- mkdocs.yml
update the table-of-content with use cases
N/A
N/A
> docs: update the table-of-content with use cases

- cmd/devstream/create.go
- cmd/devstream/main.go
- cmd/devstream/start.go
- go.mod
- go.sum
- internal/pkg/create/create.go
- internal/pkg/create/framework.go
- internal/pkg/create/language.go
- internal/pkg/start/start.go
New commands `dtm start` and `dtm create` scaffolding.
N/A
New commands `dtm start` and `dtm create` scaffolding.
> feat: new commands support: start/create

- internal/pkg/create/create.go
- internal/pkg/create/param.go
feat: interfaces definition for dtm create command
> feat: interfaces definition for dtm create command

- go.mod
- go.sum
- internal/pkg/create/create.go
- internal/pkg/create/param/github.go
- internal/pkg/create/param/param.go
- internal/pkg/create/param/repoScaffolding.go
- pkg/util/cli/status.go
- pkg/util/log/log.go
- support repo creation for cli
- support argocd creation for cli
> feat: add repo and app creation for cli prompt

- internal/pkg/start/start.go
- internal/pkg/start/tool/argocd.go
- internal/pkg/start/tool/tool.go
> fix: check argo helm repo

- docs/plugins/helm-installer/devlake.md
- docs/plugins/helm-installer/devlake.zh.md
- internal/pkg/plugin/helminstaller/defaults/devlake.go
close #1436 #1437 #1438 #1439 #1440 #1441 #1442 #1443 #1444 #1445 #1446 #1447 #1448 #1451
> fix: devlake helm repo url

- .github/workflows/e2e-test.yml
fix error: e2e build stage, not found make command
> fix: e2e build stage not found make command

- .github/ISSUE_TEMPLATE/bug-report.yaml
- cmd/patch.go
> fix: a small bug fixed
