devstream-io/devstream

.github/workflows/golangci-lint.yml
.gitignore
Makefile
README.md
cmd/devstream/main.go
docs/architecture.md

- CLI tool is renamed from `dtm` to `dsm`.
- Documentation is updated, too.
`dtm install -f ...`
`dsm install -f ...`

Rename the CLI tool from "dtm" to "dsm"

---

Makefile
README.md

- As what "Repo About" says: `DevStream: the open-source DevOps toolchain manager (DTM).` I think that we need to unify the naming with `DevOps toolchain manager` and `DevOps tool manager`. Maybe toolchan is better, so I pick this.
- `core` stage is not so clear at the Makefile. The word "core" lost the main meaning of "build". So I think build-core is better; Maybe build:core or something similar is more better. What's you opinion? @IronCore864 @lfbdev

docs: unified naming and etc.

---

internal/pkg/pluginengine/plugin.go
internal/pkg/pluginmanager/downloader.go
internal/pkg/pluginmanager/manager.go

some reflactoring with download-client/plugin-engine
- All params in DownloadClient is not used without retry.Client. So they can be removed and retry.Client.SetRetryCount() is needed.
- Impreved some exception handling.
/kind reflector
/kind bug
/cc @merico-dev/devstream please take a review at this pr. thx.

fix: some reflactoring with download-client/plugin-engine

---

cmd/argocdapp/main.go
cmd/githubactions/main.go
internal/pkg/argocdapp/argocdapp.go
internal/pkg/argocdapp/install.go
internal/pkg/argocdapp/reinstall.go
internal/pkg/argocdapp/uninstall.go
internal/pkg/githubactions/githubactions.go
internal/pkg/githubactions/reinstall.go
internal/pkg/githubactions/uninstall.go

feat: 
1.Implement uninstall/reinstall interface for argocdapp plugin
2.Implement uninstall/reinstall interface for githubactions plugin
for a argocdapp:
Reinstall: kubectl delete  +  kubectl apply again
Uninstall: kubectl delete 
for a githubaction:
Reinstall: DeleteFile  +  CreateFile from github repo
Uninstall: DeleteFile from github repo
#7  #9

add reinstall and unistall actions

---

internal/pkg/githubactions/githubactions.go
internal/pkg/githubactions/golang/templates.go
internal/pkg/githubactions/install.go
internal/pkg/githubactions/nodejs/templates.go
internal/pkg/githubactions/param.go
internal/pkg/githubactions/python/templates.go
internal/pkg/githubactions/reinstall.go
internal/pkg/githubactions/uninstall.go
internal/pkg/githubactions/workflow.go

feat: adding multi-language entrances support
#14

feat: adding multi-language entrances support

---

Makefile

make Makefile better
1. Use `go mod tidy` to instead of `go get ./...`. `go mod tidy` contains the work of `go get ./...` and does more.
Tidy makes sure go.mod matches the source code in the module.
It adds any missing modules necessary to build the current module's
packages and dependencies, and it removes unused modules that
don't provide any relevant packages. It also adds any missing entries
to go.sum and removes any unnecessary ones.
2. Add `make help` command, effect like below:
3. Add **fmt** and **vet** as two default action in `build` stage.

refactor: make Makefile better

---

cmd/devstream/install.go
internal/pkg/argocdapp/argocdapp.go
internal/pkg/argocdapp/install.go
internal/pkg/planmanager/plan.go
internal/pkg/planmanager/result.go
internal/pkg/statemanager/state.go

argocdapp installation failed & logs improved
fix #49 
fix #93

fix: #49 #93 - argocdapp installation failed & logs improved

---

Makefile
internal/pkg/argocd/argocd.go
internal/pkg/argocd/reinstall.go
internal/pkg/argocd/uninstall.go
internal/pkg/statemanager/state.go

Make argocd uninstall operation idempotent
#94 
Do not close #94 soon after this pr's merged. argocdapp is waiting for supportting uninstall operation idempotent

feat: make argocd uninstall operation idempotent

---

cmd/devstream/apply.go
cmd/devstream/init.go
cmd/devstream/main.go
internal/pkg/configloader/config.go
internal/pkg/pluginmanager/pbdownloader.go

Use viper to read in the config.yaml
It's useful for #64

Feat: Use viper to read in the config.yaml

---

.gitignore
Makefile
cmd/devstream/apply.go
cmd/devstream/init.go
cmd/devstream/main.go
examples/config.yaml
internal/pkg/backend/local/local.go
internal/pkg/configloader/config.go
internal/pkg/planmanager/change.go
internal/pkg/planmanager/plan.go
internal/pkg/planmanager/plan_helper.go
internal/pkg/planmanager/result.go
internal/pkg/plugin/argocd/argocd.go
internal/pkg/plugin/argocd/install.go
internal/pkg/plugin/argocdapp/template.go
internal/pkg/plugin/githubactions/githubactions.go
internal/pkg/plugin/githubactions/install.go
internal/pkg/pluginengine/engine.go
internal/pkg/pluginengine/helper.go
internal/pkg/pluginengine/plugin.go
internal/pkg/pluginmanager/downloader_test.go
internal/pkg/pluginmanager/manager.go
internal/pkg/pluginmanager/pbdownloader.go
internal/pkg/statemanager/state.go

Build:
- `make build` will make sure the default plugins directory exists (`.devstream`) and will build the plugins to `.devstream/*.so`
- `make fmt` changed to `go install` (starting in Go 1.17, installing executables with go get is deprecated)
Command/Engine:
- init: the logic isn't changed; apply without init will also work.
- apply: the `applyCMDFunc` is hugely reduced, moving the main logic to a new function `pluginengine.Run`
- a new helper file for the engine module is created to better organize the code structure
Configloader:
- viper initialization is moved out of the `initConfig` function (bug: `dtm` without any subcommand would fail because it tries to load the config file)
- viper UnmarshalKey is moved to `configloader.LoadConf` to reduce duplicated code
State/Backend:
- …

refactor: cmd and plugin engine modules, and fixing some bugs

---

cmd/devstream/apply.go
internal/pkg/pluginengine/apply.go
internal/pkg/pluginmanager/manager.go

This is a breaking change.
Closes #102 
Apply will init first (which will download plugins if they don't exist).
Apply WILL NOT init first. Apply only checks if needed plugins exist; if not, an error will be returned instead of downloading the plugins for the user.

refactor: only check, no download plugins before apply

---

.gitignore
Makefile
README.md
build/package/Dockerfile
build/package/build_linux_amd64.sh
internal/pkg/pluginmanager/manager.go

This PR supports building dtm and its plugins in a cross-platform manner. 
Src platform: darwin/arm64 (M1 Mac, aarch64)
| Destination platforms | Command to Build          | Method to Build | Why                                                                                          |
|-----------------------|---------------------------|-----------------|----------------------------------------------------------------------------------------------|
| darwin/arm64          | `make build-darwin-arm64` | local           | faster                                                                                       |
| darwin/amd64          | `make build-darwin-amd64` | local           | faster                                                                                       |
| …

Feat: Cross-platform Build

---

examples/config.yaml
go.mod
internal/pkg/configloader/config.go
internal/pkg/planmanager/plan_apply.go
internal/pkg/planmanager/plan_helper.go
internal/pkg/plugin/argocd/argocd.go
internal/pkg/plugin/argocdapp/install.go
internal/pkg/plugin/argocdapp/uninstall.go

- `viper` is changed to `yaml.v3` for config loading. This is because `viper` loads the object into `map[interface{}]interface{}` instead of `map[string]interface{}` (the latter of which is the state).
- `reflect.DeepEqual` is changed to `cmp.Equal`, which is intended to be a more powerful and safer alternative for comparing whether two values are semantically equal.
- bug fix: fix a bug that the argocdapp plugin only deletes the temp file in Uninstall but not in Install
- argocd app: timeout increased to 5 min. This is because, it seems that the go-helm-client doesn't do the upgrade in a `helm upgrade --install` fashion and will generate an error if the first install fails.
- some minor refactor to make the Go code more idiomatic.

feat: plugin supports multiple instances

---

README.md
cmd/devstream/apply.go
cmd/devstream/delete.go
cmd/devstream/main.go
go.mod
go.sum
internal/pkg/pluginengine/apply.go
internal/pkg/pluginengine/delete.go
internal/pkg/pluginengine/helper.go

- `dtm apply` and `dtm delete` will ask the user's input to decide if the apply/delete should continue (by default, no)
- `dtm -y apply` and `dtm -y delete` bypass the confirmation (just as `apt -y update` does)
- introduced a new third-party package that is `tcnksm/go-input` for easier handling user input
- documentation is updated as well
Closes #143

feat: apply/delete asks for confirmatin

---

README.md

- restructured the README.md, so that configuration/usage is before build/test (the reason behind this is, most viewers probably are users, or at least users first, then contributors)
- added a "dependency" subsection in the "build" section
- added a "TL;DR" (without changing the content, though) thanks to @hughluo's suggestion

doc: restructure readme and add dependencies

---

Makefile
internal/pkg/configloader/config.go

Plugin name is changed from `PLUGIN-NAME_VERSION.so` to `PLUGIN-NAME-GOOS-GOARCH_VERSION.so`.

Feat rename plugins for darwin arm64

---

examples/config.yaml
internal/pkg/plugin/argocd/reinstall.go
internal/pkg/plugin/argocd/uninstall.go
internal/pkg/plugin/kubeprometheus/reinstall.go
internal/pkg/plugin/kubeprometheus/uninstall.go
pkg/util/helm/helm.go
pkg/util/k8s/github_test.go
pkg/util/k8s/k8s.go
pkg/util/k8s/k8s_suite_test.go
pkg/util/k8s/static.go
pkg/util/k8s/workload.go

Feat: delete namespace when uninstall argocd & kube-prometheus
/cc @IronCore864 @lfbdev Please take a review at this pr tomorrow.

Feat: delete namespace when uninstall argocd & kube-prometheus

---

cmd/devstream/main.go

Fix: dtm version should only return version number without extra logging
fix #187

Fix: dtm version should only return version number without extra logging

---

pkg/util/helm/helm.go

helm param Atomic should be false when Wait is set to false

Fix: helm param Atomic should be false when Wait is set to false

---

pkg/util/helm/state.go

Fix: extra field with helm-style plugins state
fix: #219 
devstream.state
```yaml
argocd-dev_argocd:
name: argocd-dev
plugin:
kind: argocd
version: 0.0.2
options:
chart:
chart_name: argo/argo-cd
namespace: argocd
release_name: argocd
timeout: 5m
upgradeCRDs: true
wait: false
create_namespace: true
repo:
name: argo
url: https://argoproj.github.io/argo-helm
resource:
workflows: |
deployments:
- name: argocd-application-controller
ready: true
- name: argocd-dex-server
ready: true
- name: argocd-redis
ready: true
- name: argocd-repo-server
ready: true
- name: argocd-server
ready: true
```

Fix: extra field with helm-style plugins state

---

go.mod
internal/pkg/plugin/devlake/devlake.go
internal/pkg/pluginengine/change_helper.go

DevLake plugin read returns:
```
"deployments": map[string]bool{"config-ui": true, "devlake": true, "grafana": true, "mysql": true}
```
Updated to:
```
 	"deployments": map[string]interface{}{
 		"config-ui": bool(true),
 		"devlake":   bool(true),
 		"grafana":   bool(true),
 		"mysql":     bool(true),
 	},
```
Also add a little logging for easier debugging.

bug: devlake read result type map[string]bool V.S. map[string]interface{}{

---

internal/pkg/log/log.go
internal/pkg/plugin/argocd/create.go
internal/pkg/plugin/jenkins/create.go
internal/pkg/plugin/jenkins/precreate.go
internal/pkg/plugin/kubeprometheus/create.go

Skip the pv/sa/cr/crb creation when it already exists
fix #215

Fix: skip the pv/sa/cr/crb creation when it already exists

---

internal/pkg/plugin/jenkins/create.go
internal/pkg/plugin/jenkins/delete.go
internal/pkg/plugin/jenkins/postdelete.go
pkg/util/k8s/rbac.go

clear all non-helm resources when Delete() & Create() failed.

Feat: clear all non-helm resources when Delete() & Create() failed.

---

docs/plugins/trello-github-integ_plugin.md
examples/config.yaml
internal/pkg/plugin/trellogithub/helper.go
internal/pkg/plugin/trellogithub/read.go
internal/pkg/plugin/trellogithub/trellogithub.go
internal/pkg/plugin/trellogithub/workflow.go
pkg/util/trello/trello.go

1.  state file resource option: workflow dir lacks "/"
2. The board must be found in trello precisely, so we must get the boardid from state resource.
- if board found, list id(todo/doing/done) can be queried
3. add "kanban" in doc, so that to let user config the kanban name of trello

Bugfix: trello state bugfix

---

internal/pkg/pluginengine/cmd_apply.go
internal/pkg/pluginengine/cmd_delete.go
internal/pkg/pluginengine/cmd_verify.go
internal/pkg/pluginengine/pluginengine_test.go
internal/pkg/statemanager/manager.go
internal/pkg/statemanager/manager_test.go

sink the use of `backend` into `statemanager`
old usage with `statemanager.NewManager()`
```go
b, err := backend.GetBackend(backend.BackendLocal)
if err != nil {
return err
}
smgr, err := statemanager.NewManager(b)
```
new usage with `statemanager.NewManager()`
```go
smgr, err := statemanager.NewManager()
```

Feat: sink the usage of `backend` into `statemanager`

---

docs/plugins/github-repo-scaffolding-golang_plugin.md
internal/pkg/plugin/reposcaffolding/github/golang/golang.go
internal/pkg/plugin/reposcaffolding/github/golang/read.go
internal/pkg/pluginengine/change_helper.go

GitHub owner isn't strictly case-sensitive.
If your username is "IronCore864" but put "ironcore864" in the DTM config, creating repo and stuff would still work; but next time when you try to `dtm apply` again, the resource would return owner name "IronCore864" which differs from what's in the state "ironcore864", hence an "update" would be triggered, when nothing is needed here.
We have added a comment in the GitHub repo scaffolding plugin so that the user should put 
```bash
tiexin@MBA ~/work/stream $ ./dtm apply
2022-02-25 11:18:09 ℹ [INFO]  Apply started.
2022-02-25 11:18:09 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-02-25 11:18:09 ℹ [INFO]  Change added: golang-demo-repo -> Create
2022-02-25 11:18:11 ℹ [INFO]  Start …
```

Bug fix GitHub repo scaffolding owner case sensitive

---

internal/pkg/plugin/jenkins/read.go
internal/pkg/plugin/kubeprometheus/read.go

Fix: helm-style plugins Read() don't return the state with ready workflows
fix #231 
see the #231 for the current behavior.
```sh
2022-02-25 13:17:17 ℹ [DEBUG]  Tool kube-prometheus-dev state and resource are the same, not drifted, do nothing.
2022-02-25 13:17:17 ℹ [DEBUG]  Changes for the plan:
2022-02-25 13:17:17 ℹ [INFO]  No changes done since last apply. There is nothing to do.
2022-02-25 13:17:17 ✔ [SUCCESS]  Apply finished.
```

Fix: helm-style plugins Read() don't return the state with ready workflows

---

Makefile
cmd/devstream/version.go
cmd/devstream/version/version.go
internal/pkg/version/version.go

Move the `internal/pkg/version` inside the `cmd/devstream/`
The `version` package is very very simple, with almost no logic, just a simple variable there. So it is unnecessary to put it under `internal/pkg`. 
But we can't put this line of code directly into `cmd/devstream/version.go`, because its different directory name and package name will cause the `go build xxx` failed. 
So it is still necessary to keep the `version` package, but this package can be hidden inside the `cmd/devstream`, so as to be less noticed by the code readers.

Refactor: move the `internal/pkg/version` inside the `cmd/devstream/`

---

ROADMAP.md

Adding the ROADMAP.md for 2022, which is a requirement for entering the CNCF sandbox.

doc: add roadmap document for 2022

---

Makefile
docs/config_state_resource_explanation.md
internal/pkg/configloader/validation.go
internal/pkg/pluginengine/change_helper.go

_Note that this is a breaking change._ See the following sections for more details.
If a _Tool_ had been created by `dtm`, then got deleted from the _Config_, `dtm apply` _wouldn't generate any change_ for it.
If a _Tool_ had been created by `dtm`, then got deleted from the _Config_, `dtm apply` would _generate a "Delete" change_ for it.

feat: `dtm apply` will delete tools that are no longer in the config

---

Makefile

Fix: Makefile e2e stage error
The `build` stage at the Makefile will generate the executable file `dtm-${GOOS}-${GOARCH}`.
So the e2e stage will fail to execute `./dtm apply -f config.yaml`.
It should be `dtm-${GOOS}-${GOARCH} apply -f config.yaml`.

Fix: Makefile e2e stage error

---

README.md
cmd/devstream/destroy.go
cmd/devstream/main.go
internal/pkg/pluginengine/cmd_destroy.go

Feat: `dtm destroy` command
```sh
2022-03-01 21:35:30 ℹ [INFO]  Destroy started.
2022-03-01 21:35:30 ℹ [INFO]  Change added: golang-demo1_github-repo-scaffolding-golang -> Delete
2022-03-01 21:35:35 ℹ [INFO]  Start executing the plan.
2022-03-01 21:35:35 ℹ [INFO]  Changes count: 1.
2022-03-01 21:35:35 ℹ [INFO]  -------------------- [  Processing progress: 1/1.  ] --------------------
2022-03-01 21:35:35 ℹ [INFO]  Processing: golang-demo1 -> Delete ...
2022-03-01 21:35:37 ✔ [SUCCESS]  GitHub repo golang-demo removed.
2022-03-01 21:35:37 ℹ [INFO]  Prepare to delete 'golang-demo1_github-repo-scaffolding-golang' from States.
2022-03-01 21:35:37 ✔ [SUCCESS]  Plugin golang-demo1 delete done.
2022-03-01 …
```

Feat: `dtm destroy` command

---

cmd/devstream/verify.go
docs/commands_in_detail/verify.md
internal/pkg/configloader/config.go
internal/pkg/plugin/githubactions/golang/create.go
internal/pkg/plugin/githubactions/golang/delete.go
internal/pkg/plugin/githubactions/golang/read.go
internal/pkg/plugin/githubactions/golang/update.go
internal/pkg/plugin/githubactions/nodejs/create.go
internal/pkg/plugin/githubactions/nodejs/delete.go
internal/pkg/plugin/githubactions/nodejs/read.go
internal/pkg/plugin/githubactions/nodejs/update.go
internal/pkg/plugin/githubactions/python/create.go
internal/pkg/plugin/githubactions/python/delete.go
internal/pkg/plugin/githubactions/python/read.go
internal/pkg/plugin/githubactions/python/update.go
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/change_helper.go
internal/pkg/pluginengine/cmd_apply.go
internal/pkg/pluginengine/cmd_delete.go
internal/pkg/pluginengine/cmd_verify.go
pkg/util/github/repo.go

1. dtm verify should not "fail" or "error" in any circumstances. The purpose of the "verify", as the word means, is to make sure if something is as expected.
2. The "error" in the log is a bit too much. If an "error" message is displayed, the user might think something went wrong or something they did is wrong, which isn't the case in the original post's issue.
3. we should have dedicated documentation explaining how everything works.
Closes #255
Closes #252 
```bash
$ ./dtm verify
2022-03-03 11:03:15 ℹ [INFO]  Verify started.
2022-03-03 11:03:15 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-03-03 11:03:15 ℹ [INFO]  Tool < golang-demo-repo > found in config but doesn't exist in the state, will be created.
2022-03-03 11:03:15 ℹ [INFO]  Tool < golang-demo-app > found in config but …
```

feat: dtm verify logic and logging improvement

---

.gitignore
hack/terraform/.terraform.lock.hcl
hack/terraform/config.tf
hack/terraform/main.tf
hack/terraform/modules/eks/README.md
hack/terraform/modules/eks/cluster.tf
hack/terraform/modules/eks/cluster_roles.tf
hack/terraform/modules/eks/control_plane_sg.tf
hack/terraform/modules/eks/nodegroup.tf
hack/terraform/modules/eks/output.tf
hack/terraform/modules/eks/variables.tf
hack/terraform/modules/eks/worker_node_roles.tf
hack/terraform/modules/eks/worker_node_sg.tf
hack/terraform/modules/networking/README.md
hack/terraform/modules/networking/gateway.tf
hack/terraform/modules/networking/output.tf
hack/terraform/modules/networking/routing_table.tf
hack/terraform/modules/networking/subnet.tf
hack/terraform/modules/networking/variables.tf
hack/terraform/modules/networking/vpc.tf

This PR creates two Terraform modules, one is for AWS VPC (and networking related,) and the other is for AWS EKS.
The VPC module has been tested; due to cost issues, the EKS module hasn't been tested yet; it will be tested later when we need to run a DTM test.
Notes:
- Terraform uses a remote state (S3, bucket created manually).
- State-lock isn't implemented yet since we are a very small team so there is no need to bring in DynamoDB TF state lock yet.

feat: Terraform for AWS VPC/EKS

---

Makefile
build/package/build_linux_amd64.sh
cmd/jiragithub/main.go
docs/plugins/jira-github-integ_plugin.md
examples/config.yaml
internal/pkg/plugin/jiragithub/create.go
internal/pkg/plugin/jiragithub/delete.go
internal/pkg/plugin/jiragithub/helper.go
internal/pkg/plugin/jiragithub/options.go
internal/pkg/plugin/jiragithub/read.go
internal/pkg/plugin/jiragithub/render.go
internal/pkg/plugin/jiragithub/templates.go
internal/pkg/plugin/jiragithub/update.go
internal/pkg/plugin/jiragithub/validation.go
internal/pkg/plugin/jiragithub/workflow.go

Add  jira-github-integ plugin
- when create a issue from github, it will be created in jira todo
-  when comment a issue from github, it will be commented in jira 
-  when edit a issue from github, it will be moved to in progress in jira 
-  when close a issue from github, it will be moved to done in jira 
-  when reopen a issue from github, it will be moved to todo in jira 

Feat: add jira-github-integ plugin

---

internal/pkg/plugin/githubactions/golang/create.go
internal/pkg/plugin/githubactions/golang/delete.go
internal/pkg/plugin/githubactions/golang/options.go
internal/pkg/plugin/githubactions/golang/render.go
internal/pkg/plugin/githubactions/golang/update.go

when docker section config is empty, dtm will raise errors
resolution
1. remove docker section validation
2. add if condition
3. when docker section is empty in render template, let it be false
#264

bug: GitHub Actions Plugin fails when Docker section doesn't exist

---

docs/plugins/argocd_plugin.md
pkg/util/helm/param.go

feat: enable values.yaml feature for apps installed by helm
The following is `test.yaml`. I want to install argocd in k8s and change the redis image version to 6.2.6-alpine3.15 and controller service's port to 8080 by `values_yaml` field in `test.yaml`.
```yaml
tools:
- name: argocd
plugin:
kind: argocd
version: 0.2.0
options:
create_namespace: true
repo:
name: argo
url: https://argoproj.github.io/argo-helm
chart:
chart_name: argo/argo-cd
release_name: argocd
namespace: argocd
wait: true
timeout: 10m
upgradeCRDs: true
values_yaml: |
controller:
service: 
port: 8080
redis:
image:
tag: 6.2.6-alpine3.15
```
```yaml
✅ 😁 ./dtm-darwin-arm64 apply -f test.yaml 
2022-03-04 21:39:54 ℹ [INFO]  Apply started.
2022-03-04 21:39:54 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-03-04 21:39:54 …
```

feat: enable values.yaml feature for apps installed by helm

---

.github/workflows/lint-commit-message.yml
build/ci/commitlint.config.js

- add `commitlint.config.js` for commit lint tool to support `doc` type in commit message
Default commit lint doesn't support `doc` type, however somebody may be used to using `doc` instead of `docs`, I hope it is acceptable.
When you use `doc` type in commit message, the commit-lint stage can't pass
Both `doc` and `docs` are allowed

ci: support `doc` type in commit message

---

docs/plugins/argocd_plugin.md
docs/plugins/jenkins_plugin.md
docs/plugins/kube-prometheus_plugin.md
internal/pkg/plugin/jenkins/create.go

Now we have opened the customize `values.yaml` function , so the logic with `values.yaml` of `Jenkins` needs to be modified accordingly.
See the issue/pr below for more info.
#272 #274

feat!: no longer configure default values for Jenkins values.yaml in the code

---

internal/pkg/plugin/trellogithub/create.go
internal/pkg/plugin/trellogithub/delete.go
internal/pkg/plugin/trellogithub/github.go
internal/pkg/plugin/trellogithub/helper.go
internal/pkg/plugin/trellogithub/read.go
internal/pkg/plugin/trellogithub/trellogithub.go
internal/pkg/plugin/trellogithub/update.go
internal/pkg/plugin/trellogithub/workflow.go

There are many functions in the `trellogithub` package that are duplicated in `util/github`, so we can delete these functions and directly refer to `util/github`.
But there are still some functions that are not implemented in `util/github`, so part of the functions is not easy to refactor for now. Later we need to spend some time for letting the `trellogithub` without any line of code directly use the `"github.com/google/go-github/v42/github"`.

refactor: using `util/github` in `trellogithub`

---

pkg/util/log/logwrapper.go

1. add add log stack print for error
2. ignore logrus stack level
#281

feat: add log stack print for error

---

pkg/util/log/logwrapper.go

Reverts merico-dev/stream#283
For the Github Actions workflow `build(ut)` failed.

Revert "feat: add log stack print for error"

---

Makefile
README.md
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/change_helper.go
internal/pkg/pluginengine/helper.go
internal/pkg/pluginengine/pluginengine_test.go
internal/pkg/statemanager/manager.go
internal/pkg/statemanager/manager_test.go
internal/pkg/statemanager/state.go

refactor: use type StateKey for the key of `state`
Since the format of the key with `state` is not randomly generated(we used a `name_kind` format), we need a `keyFunc` to generate this key.
Therefore, avoiding the use of the basic type `string` can make developers pay attention NOT to use a `casual string` as a key, but to call the corresponding `keyFunc` to generate it.
We've inadvertently fallen into the "string" trap more than once, such as:
1. #282
2. #285
So I think it is more "robust" to use the `StateKey` type as the state key.
- statemanager/state.go 64
```go
// Note: Please use the StateKeyGenerateFunc function to generate StateKey instance.
type StateKey string
```

refactor: use type StateKey for the key of `state`

---

pkg/util/log/logwrapper.go

print log stacktrace only when log level is debug
if  you still want to print error stack, use "--debug" option, or it will not print stack

fix: print log stack when debug

---

pkg/util/github/repo.go

fix: panic for `nil pointer dereference` in util/github
close #302

fix: panic for `nil pointer dereference` in util/github

---

cmd/devstream/main.go
pkg/util/github/github.go
pkg/util/k8s/k8s.go

Support setting kubeconfig from env
To support running e2e tests in `GitHub actions`, `dtm` needs to be able to get `kubeconfig` from a "non-default" address(eg: /github/home/.kube/config in the eks action base image).
Perhaps it is not the most appropriate to configure this `kubeconfig path` by `environment variables`. But at present our `config.yaml` is all about plugin-related configuration, no core-related. So I made a compromise and implemented it in this way first.
Later, if necessary, I will add this type(non-secret) of configuration to config.yaml, that is, when we determine that `config.yaml` needs to contain the non-secret configuration of `dtm-core`

feat: support setting kubeconfig from env

---

docs/plugins/argocdapp_plugin.md
docs/plugins/github-repo-scaffolding-golang_plugin.md
docs/plugins/githubactions-golang_plugin.md
internal/pkg/plugin/reposcaffolding/github/golang/golang.go
internal/pkg/plugin/reposcaffolding/github/golang/read.go
pkg/util/github/repo.go

- docs update for argocdapp/github scaffolding/github actions plugin
- add outputs for github actions plugin
- backwards compatible/non-breaking change (tested, state/core not affected by added output)

feat: add outputs for github repo scaffolding plugin

---

internal/pkg/pluginengine/change.go

When the user names different plugin instances as `demo-x` , the absence of `kind` information will make the logs very `hard to read`.

doc: adding `kind` in the log msg

---

docs/plugins/trello-github-integ_plugin.md
docs/plugins/trello_plugin.md
internal/pkg/plugin/trello/helper.go
internal/pkg/plugin/trello/trello.go
internal/pkg/plugin/trellogithub/create.go
internal/pkg/plugin/trellogithub/delete.go
internal/pkg/plugin/trellogithub/helper.go
internal/pkg/plugin/trellogithub/read.go
internal/pkg/plugin/trellogithub/trellogithub.go
internal/pkg/plugin/trellogithub/update.go
internal/pkg/plugin/trellogithub/workflow.go
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/change_helper.go
internal/pkg/pluginengine/cmd_apply.go
internal/pkg/pluginengine/fillRefValueWithOutputs_test.go
internal/pkg/pluginengine/getOutputs_test.go
internal/pkg/statemanager/manager.go
internal/pkg/statemanager/state.go
pkg/util/trello/trello.go

Use format: ${{ TOOL_NAME.TOOL_KIND.outputs.var}} to ref the outputs of other plugins
#324

feat: add plugin outputs reference

---

cmd/devstream/develop.go
cmd/devstream/main.go
internal/pkg/develop/develop.go
internal/pkg/develop/plugin/create.go
internal/pkg/develop/plugin/plugin.go
internal/pkg/develop/plugin/template/NAME.go
internal/pkg/develop/plugin/template/NAME_plugin.md.go
internal/pkg/develop/plugin/template/README_when_create_plugin.md.go
internal/pkg/develop/plugin/template/create.go
internal/pkg/develop/plugin/template/delete.go
internal/pkg/develop/plugin/template/main.go
internal/pkg/develop/plugin/template/options.go
internal/pkg/develop/plugin/template/read.go
internal/pkg/develop/plugin/template/template.go
internal/pkg/develop/plugin/template/update.go
internal/pkg/develop/plugin/template/validate.go

feat: `dtm develop create-plugin` implement
This pr only contains code implementation, and the corresponding usage documentation is left in a separate pr, perhaps on the blog we will run recently.
- `./dtm-darwin-arm64 develop create-plugin --name="foo"`
```sh
2022-03-18 13:23:20 ℹ [INFO]  Render template files finished.
2022-03-18 13:23:20 ℹ [INFO]  Persist all files finished.
The DevStream PMC (project management committee) sincerely thank you for your devotion and enthusiasm in creating new plugins!
To make the process easy as a breeze, DevStream(dtm) has generated some templated source code files for you to flatten the learning curve and reduce manual copy-paste.
In the generated templates, dtm has left some special marks in the format of …
```

feat: `dtm develop create-plugin` implement

---

internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/cmd_apply.go

delete unnecessary logs in `handle-result`
```sh
2022-03-18 22:32:17 ℹ [INFO]  -------------------- [  Processing progress: 1/1.  ] --------------------
2022-03-18 22:32:17 ℹ [INFO]  Processing: golang-demo2(kind: github-repo-scaffolding-golang) -> Create ...
2022-03-18 22:32:22 ✖ [ERROR]  The tool < golang-demo2/github-repo-scaffolding-golang > Create failed.
2022-03-18 22:32:22 ℹ [INFO]  -------------------- [  Processing done.  ] --------------------
2022-03-18 22:32:22 ✖ [ERROR]  Error: key(github-repo-scaffolding-golang/golang-demo2-Create) -> msg: environment variable GITHUB_TOKEN is not set. Failed to initialize GitHub token. More info - https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-acc …
```

fix: delete unnecessary logs in `handle-result`

---

internal/pkg/plugin/argocd/state.go

ArgoCD old deployments:
```sh
"argocd-application-controller",
"argocd-dex-server",
"argocd-redis",
"argocd-repo-server",
"argocd-server",
```
ArgoCD new deployments:
```sh
"argocd-applicationset-controller",
"argocd-dex-server",
"argocd-notifications-controller",
"argocd-redis",
"argocd-repo-server",
"argocd-server",
```
For this difference, the `argocd` plugin will `update` when apply twice.
---
- `./dtm-darwin-arm64 apply -f config-argocd.yaml`
```sh
2022-03-18 23:45:23 ℹ [INFO]  Apply started.
2022-03-18 23:45:23 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-03-18 23:45:23 ℹ [INFO]  Tool < argocd-dev > found in config but doesn't exist in the state, will be created.
2022-03-18 …
```

fix: argocd plugin apply twice trigger update

---

internal/pkg/plugin/argocd/create.go
internal/pkg/plugin/argocd/update.go
internal/pkg/plugin/common/helm/helm.go
internal/pkg/plugin/jenkins/create.go
internal/pkg/plugin/jenkins/update.go
internal/pkg/plugin/kubeprometheus/create.go
internal/pkg/plugin/kubeprometheus/update.go
internal/pkg/plugin/openldap/create.go
internal/pkg/plugin/openldap/update.go

feat(helm-style plugins): update without delete
update=delete+create
Both `create` and `update` use the `InstallOrUpgradeChart()` as a main process. The difference is:
- `create` needs to deal with `ns` create/delete` logic
- `update` doesn't need to deal with `ns` create/delete` logic
1. `./dtm-darwin-arm64 apply -f config-argocd.yaml`
```sh
2022-03-19 14:00:43 ℹ [INFO]  Apply started.
2022-03-19 14:00:43 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-03-19 14:00:43 ℹ [INFO]  Tool < argocd-dev > found in config but doesn't exist in the state, will be created.
2022-03-19 14:00:45 ℹ [INFO]  Start executing the plan.
2022-03-19 14:00:45 ℹ [INFO]  Changes count: 1.
2022-03-19 14:00:45 ℹ …
```

feat(helm-style plugins): update without delete

---

docs/architecture.md
docs/commands_explained.md
docs/core_concepts.md
docs/index.md
docs/quickstart_en.md
docs/quickstart_zh.md
internal/pkg/pluginengine/change_helper.go

Thanks @[algobot76](https://github.com/merico-dev/stream/issues?q=is%3Aissue+is%3Aopen+author%3Aalgobot76) for contributing a doc related issue!
- core_concept.md renamed to core_concepts.md
- command related explanation is moved out of core_concepts.md and into a new doc commands_explained.md
- `dtm destroy` doc is added into commands_explained.md
- reorder the docs in [readthedocs.io
](https://docs.dtm.dev/en/latest/) to make it more logical
- minor comment format update in one src file
Closes #339

Docs dtm destroy

---

internal/pkg/develop/plugin/template/main.go

Unify parameters originally named params into options for `main.go` template

chore: change params to options for main.go template

---

internal/pkg/develop/plugin/template/main.go

The main.go file of the plugin has been moved from `/cmd/{plugin_name}/main.go` to `/cmd/plugin/{plugin_name}/main.go`, but the template of the plugin generation tool is not synchronized, this commit fixes the problem

fix: change main_go_dir to `cmd/plugin/`

---

.github/workflows/main-builder.yml

It's my fault, I didn't know the name would show up here before. 
In other words, if it needs to show here, I think the `main builder` is more suitable.

chore: revert the workflow name with 'main builder'

---

Makefile
README.md

Thanks @algobot76 for raising this issue. This PR reorganized our makefile so that we could simply run "make build -j8" to speed things up.
Ideal releasing process:
- make clean
- make build -j8
- make release
This will be reflected in a release document soon.
Also, some re-order, adding/removing empty lines are done, so that the Makefile is more human-readable.
Closes #361 
```shell
tiexin@MBA ~/work/stream $ make clean && \time make build -j8
rm -rf .devstream
rm -f dtm*
rm -f *.md5
rm -rf build/working_dir
go install golang.org/x/tools/cmd/goimports@latest
go vet ./...
go mod tidy
mkdir -p .devstream
goimports -local="github.com/merico-dev/stream" -d -w cmd
goimports -local="github.com/merico-dev/stream" -d -w pkg
goimports -local="github.com/merico-dev/stream" -d -w internal
goimports …
```

ci: improve makefile for multi-threaded build and readme

---

Makefile
cmd/devstream/version.go
cmd/devstream/version/version.go
internal/pkg/configloader/config.go
internal/pkg/configloader/configloader_test.go
internal/pkg/configloader/validation.go
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/change_helper.go
internal/pkg/pluginengine/pluginengine_test.go
internal/pkg/pluginengine/topological_sort.go
internal/pkg/pluginengine/topological_sort_test.go
internal/pkg/pluginmanager/manager.go
internal/pkg/pluginmanager/pluginmd5_test.go
internal/pkg/statemanager/manager_test.go
internal/pkg/statemanager/state.go
internal/pkg/version/version.go

Remove "version" from "plugin" in the config.
_Doc hasn't been updated yet._
Since core and plugin must be built at the same time, the "version" is redundant information now in the config.
Config:
```yaml
tools:
- name: ABC
plugin:
kind: argocd
version: 0.3.0
```
Config:
```yaml
tools:
- name: ABC
plugin: argocd
```

feat: remove plugin version from config

---

.github/workflows/automated-release.yml
.github/workflows/main-builder.yml

fix: install goimports at `main builder` & `automated-release` workflow
#368

fix: install goimports at `main builder` & `automated-release` workflow

---

.github/workflows/golangci-lint.yml

fix: golang lint ci failed
Just now I found out that one of the contributor's pr(#385 ) failed in ci workflow:
https://github.com/devstream-io/devstream/runs/5814780108?check_suite_focus=true
This problem is not introduced by this pr, but: https://github.com/golangci/golangci-lint-action/issues/434
So the solution here should be:
1. set up `skip-go-installation: true` in v2
2. upgrade `golangci-lint-action` to v3 - (I choose this)

fix: golang lint ci failed

---

README.md
docs/README_zh.md

- Doc about installation instructions.
- A few fixes, including deleting extra whitespace and adding missing empty lines.
Close #372 
n/a
n/a
n/a
n/a

doc: installation on mac

---

Makefile
cmd/devstream/list.go
cmd/devstream/main.go
internal/pkg/list/list.go
internal/pkg/list/plugins/list.go

View all supported plugins with the command:
`dtm list plugins`
and in Makefile: 
`ldflags  parameter` is too long, extract the `DEVSTREAM_INTER_PKG` and `GO_LDFLAGS` parameter
#384

feat(cmd): support  list command

---

docs/best_practices.md
docs/best_practices/gitops.md
docs/commands_in_detail/verify.md
docs/conf.py
docs/creating_a_document.md
docs/index.md
docs/plugins.md
docs/plugins/argocd.md
docs/plugins/argocdapp.md
docs/plugins/devlake.md
docs/plugins/github-repo-scaffolding-golang.md
docs/plugins/githubactions-golang.md
docs/plugins/githubactions-nodejs.md
docs/plugins/githubactions-python.md
docs/plugins/gitlabci-golang.md
docs/plugins/jenkins.md
docs/plugins/jira-github-integ.md
docs/plugins/kube-prometheus.md
docs/plugins/openldap.md
docs/plugins/trello-github-integ.md
docs/plugins/trello.md

- Created a document on how to create documents.
- Refactored the title level of existing documents (mainly on plugins.)
- Add best practices documents into the table of content so that it can show up in the docs.

docs: add a doc of docs, and refactor existing docs

---

ROADMAP.md

docs: update roadmap accordig to recent changes

---

cmd/devstream/list/list.go
internal/pkg/show/config/config.go
internal/pkg/show/config/plugin/jenkins.go
internal/pkg/show/config/plugin/jira-github-integ.go
internal/pkg/show/config/plugin/kube-prometheus.go
internal/pkg/show/config/plugin/openldap.go
internal/pkg/show/config/plugin/trello-github-integ.go
internal/pkg/show/config/plugin/trello.go

1. Support default config print logic
2. Sorting the output of the list command
#383

Feat: Support default config print logic by @summingyu

---

.github/workflows/e2e-test.yml
internal/pkg/pluginengine/outputs.go
internal/pkg/pluginengine/outputs_test.go
internal/pkg/pluginengine/pluginengine_test.go
test/e2e/yaml/e2e-config.yaml

- New feature: now outputs support string interpolation. For example: `helm/${{ repo.github-repo-scaffolding-go.outputs.repo }}` can be used as a value.
- e2e tests: added repo scaffolding -> github actions -> argocd -> argocd app -> verify pod.

feat: outputs support interpolation; add more e2e tests

---

README.md

Use Slack instead of Discord as Slack is more popular.
- Documentation (existing) is updated.
Replace the Discord badge with a Slack one in README.

docs(README): replace discord badge with slack

---

internal/pkg/plugin/githubactions/common.go
internal/pkg/plugin/githubactions/golang/create.go
internal/pkg/plugin/githubactions/golang/update.go
internal/pkg/plugin/githubactions/nodejs/create.go
internal/pkg/plugin/githubactions/nodejs/update.go
internal/pkg/plugin/githubactions/python/create.go
internal/pkg/plugin/githubactions/python/update.go
internal/pkg/plugin/reposcaffolding/github/golang/golang.go
internal/pkg/plugin/reposcaffolding/github/golang/read.go
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/change_helper.go
internal/pkg/pluginengine/cmd_destroy.go
internal/pkg/statemanager/manager_test.go
internal/pkg/statemanager/state.go
test/e2e/yaml/e2e-config.yaml

- added dependsOn into state
- added a new method to StatesMap so that it can be converted to a list (used for easy sorting)
- fixed the order issue with destroy/force delete
- fixed failed e2e-test and org/owner related issue
Closes #402 
See issue #402 
Destroy and force delete now honor the dependsOn settings.

Fix destroy force delete order issue

---

internal/pkg/statemanager/manager_test.go
internal/pkg/statemanager/state.go

/kind bug
fix: make state.ToList stable

fix: make state.ToList stable

---

.github/workflows/automated-release.yml
.github/workflows/e2e-test.yml
.github/workflows/lint-commit-message.yml
internal/pkg/plugin/reposcaffolding/github/golang/golang.go
internal/pkg/pluginengine/change.go
pkg/util/github/repo.go

**Scope: The GITHUB_TOKEN is scoped to the repository running the workflow. It cannot be used to make changes to any other repositories.**
---
The error we saw:
The permission we used:

ci: use the test account to run the e2e

---

.gitignore
cmd/devstream/apply.go
cmd/devstream/delete.go
cmd/devstream/init.go
cmd/devstream/main.go
cmd/devstream/verify.go
internal/pkg/configloader/config.go
internal/pkg/configloader/variables.go
internal/pkg/configloader/variables_test.go
internal/pkg/pluginengine/cmd_apply.go
internal/pkg/pluginengine/cmd_delete.go
internal/pkg/pluginengine/cmd_verify.go

Config file now supports the use of variables. 
- Use `dtm --var-file` to specify the location of the var file. Defaults to `variables.yaml`.
- If no --var-file is specified, and `variables.yaml` doesn't exist, continue without an error.
Related to #393 but not totally finished yet. Another PR of documentation with e2e test comes soon.
```shell
tiexin@mbp ~/work/stream $ ./dtm --debug apply -f config-variables.yaml
2022-04-14 15:40:43 ℹ [INFO]  Log level is: debug.
2022-04-14 15:40:43 ℹ [INFO]  Apply started.
2022-04-14 15:40:43 ℹ [DEBUG]  Original config:
tools:
- name: myapp
plugin: gitlabci-generic
options:
pathWithNamespace: [[ gitlabUser ]]/go-hello-world
branch: [[ defaultBranch ]]
templateURL: [[ gitlabCIGolangTemplate ]]
templateVariables:
App: hello
2022-04-14 15:40:43 ℹ [DEBUG] …
```

feat: config supports variables

---

docs/plugins/argocd.md
docs/plugins/devlake.md
docs/plugins/github-repo-scaffolding-golang.md
docs/plugins/gitlabci-generic.md
docs/plugins/gitlabci-golang.md
docs/plugins/jenkins.md
docs/plugins/jira-github-integ.md
docs/plugins/kube-prometheus.md
docs/plugins/openldap.md
docs/plugins/trello-github-integ.md
docs/plugins/trello.md
internal/pkg/show/config/plugin/argocd.go
internal/pkg/show/config/plugin/devlake.go
internal/pkg/show/config/plugin/github-repo-scaffolding-golang.go
internal/pkg/show/config/plugin/gitlabci-generic.go
internal/pkg/show/config/plugin/gitlabci-golang.go
internal/pkg/show/config/plugin/jenkins.go
internal/pkg/show/config/plugin/jira-github-integ.go
internal/pkg/show/config/plugin/kube-prometheus.go
internal/pkg/show/config/plugin/openldap.go
internal/pkg/show/config/plugin/trello-github-integ.go
internal/pkg/show/config/plugin/trello.go

Adding the missing config field for most plugins.

chore: adding the missing config field for most plugins.

---

go.mod
go.sum

All of subcommands' help information  are starting with uppercase letters, except for `completion`. cobra 1.3.0 has resolved this issue. I do not know why the version is not automatically updated, so manually update to the latest version 1.4.0.
N/A
```bash
completion  generate the autocompletion script for the specified shell
```
```bash
completion  Generate the autocompletion script for the specified shell
```
N/A
N/A

fix: completion help info first letters lowercase

---

internal/pkg/plugin/common/reposcaffolding/download.go
internal/pkg/plugin/common/reposcaffolding/helper.go
internal/pkg/plugin/common/reposcaffolding/options.go
internal/pkg/plugin/common/reposcaffolding/reposcaffolding.go
internal/pkg/plugin/reposcaffolding/github/golang/create.go
internal/pkg/plugin/reposcaffolding/github/golang/delete.go
internal/pkg/plugin/reposcaffolding/github/golang/golang.go
internal/pkg/plugin/reposcaffolding/github/golang/options.go
internal/pkg/plugin/reposcaffolding/github/golang/read.go
internal/pkg/plugin/reposcaffolding/github/golang/update.go

Refactor: this PR should not change any functions.
A new package `internal/pkg/plugin/common/reposcaffolding/` is created for the following logic:
- download the template repo
- unzip
- walk downloaded template repo and render templates to local files
Then, `github-repo-scaffolding-golang` plugin is updated to:
- use `internal/pkg/plugin/common/reposcaffolding/` pkg
```shell
tiexin@mbp ~/work/stream $ ./dtm apply
2022-04-24 15:55:17 ℹ [INFO]  Apply started.
2022-04-24 15:55:17 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-04-24 15:55:17 ℹ [INFO]  Tool github-repo-scaffolding-golang (default) found in config but doesn't exist in the state, will be created.
2022-04-24 15:55:19 ℹ [INFO]  Start executing the plan.
2022-04-24 15:55:19 ℹ …
```

Refactor: GitHub repo scaffolding common pkg

---

Makefile

- No more hard-coding VERSION variable in the `Makefile`. Don't need to modify the value of VERSION when you release `dtm`, just execute this command `make build VERSION=xxx`
- Use a more native way to get plugins list. `PLUGINS=$(notdir $(wildcard $(ROOT_DIR)/cmd/plugin/*))`

chore: optimize Makefile

---

cmd/devstream/develop.go
internal/pkg/develop/develop.go
internal/pkg/develop/plugin/plugin.go
internal/pkg/develop/plugin/template/NAME.go
internal/pkg/develop/plugin/template/create.go
internal/pkg/develop/plugin/template/delete.go
internal/pkg/develop/plugin/template/main.go
internal/pkg/develop/plugin/template/template.go
internal/pkg/develop/plugin/validate.go

new develop validate-plugin command,
1.  add `MustExistFlag bool` to TplFile and File struct  of `internal/pkg/develop/plugin/template/template.go`
2. add `var xxx_go_mustExistFlag = true` to `internal/pkg/develop/plugin/template/create.go` and some need validate file
3. Render template files
4. Validate need validate files
5. if MustExistFlag is true, validate file.Dir and file.Name
#436 
```bash
$ for plugin in `./dtm list plugins`;do ./dtm develop validate-plugin --name="$plugin" 2>&1;done
2022-05-04 10:12:46 ℹ [INFO]  Render template files finished.
2022-05-04 10:12:46 ✖ [ERROR]  Failed to validate: internal/pkg/plugin/argocd/argocd.go.
2022-05-04 10:12:46 ✖ [ERROR]  stat internal/pkg/plugin/argocd/argocd.go: no such file or directory
2022-05-04 10:12:46 ℹ [INFO]  Plugin argocd passed …
```

feat: new develop validate-plugin command

---

cmd/plugin/helm-generic/main.go
internal/pkg/plugin/common/helm/helm.go
internal/pkg/plugin/helmgeneric/create.go
internal/pkg/plugin/helmgeneric/delete.go
internal/pkg/plugin/helmgeneric/helmgeneric.go
internal/pkg/plugin/helmgeneric/read.go
internal/pkg/plugin/helmgeneric/state.go
internal/pkg/plugin/helmgeneric/update.go
internal/pkg/plugin/helmgeneric/validate.go
internal/pkg/show/config/config.go
internal/pkg/show/config/plugin/helm-generic.go

add a new plugin for helm-type plugin install
see the proposal https://github.com/devstream-io/devstream/issues/424
#424

feat: add helm generic plugin

---

internal/pkg/statemanager/state.go

Fixed a typo in internal/pkg/statemanager/state.go

fix: fix a typo in state.go

---

cmd/devstream/develop.go
internal/pkg/develop/plugin/validate.go

1. Add `--all` flag to command `dtm develop validate-plugin` to validate all existing plugins.
2. Add a new function `ValidatePlugins` which will call function `ValidatePlugin`(old name is Validate).
#443 
```
{22-05-07 14:23}hxc-macbook-air:devstream@main✗✗✗✗✗✗ hxc% ./dtm develop validate-plugin --all 
2022-05-07 14:24:31 ℹ [INFO]  Validate all plugins.
2022-05-07 14:24:31 ℹ [INFO]  Render template files finished.
2022-05-07 14:24:31 ✖ [ERROR]  Failed to validate: internal/pkg/plugin/argocd/argocd.go.
2022-05-07 14:24:31 ✖ [ERROR]  stat internal/pkg/plugin/argocd/argocd.go: no such file or directory
2022-05-07 14:24:31 ✔ [SUCCESS]  Plugin <argocd> passed validation.
2022-05-07 14:24:31 ℹ [INFO]  Validate all files finished.
2022-05-07 14:24:31 ℹ [INFO]  Render template files finished. …
```

feat(command): new develop validate-plugin flag --all

---

internal/pkg/develop/plugin/plugin.go
internal/pkg/develop/plugin/validate.go
internal/pkg/plugin/argocd/argocd.go
internal/pkg/plugin/jenkins/jenkins.go
internal/pkg/plugin/openldap/openldap.go

Some small changes with `validate-plugin` command
#443 
#436
@summingyu I slightly optimized the log printing and added lost files to some plugins. Now many of the remaining plugins fail to pass the verification is not a problem of plugins, but a problem of verification rules. For example, the package name of plugin `kube-prometheus` is `kubeprometheus`, which is actually reasonable. So our validation rules need to be more precise.
```sh
./dtm develop  validate-plugin --all                                                                                            
2022-05-08 22:42:53 ℹ [INFO]  Start validating all plugins.
2022-05-08 22:42:53 ℹ [INFO]  ===== start validating <argocd> =====
2022-05-08 22:42:53 ✔ [SUCCESS]  Plugin <argocd> passed …
```

Fix: some small changes with `validate-plugin` command

---

internal/pkg/develop/plugin/plugin.go
internal/pkg/develop/plugin/template/NAME.go
internal/pkg/develop/plugin/template/create.go
internal/pkg/develop/plugin/template/delete.go
internal/pkg/develop/plugin/template/funcmaps.go
internal/pkg/develop/plugin/template/main.go
internal/pkg/develop/plugin/template/options.go
internal/pkg/develop/plugin/template/read.go
internal/pkg/develop/plugin/template/update.go
internal/pkg/develop/plugin/template/validate.go

1. fix issues #454
2. add a new file `funcmaps.go`
#454

feat:  dtm develop create-plugin enhancement

---

cmd/devstream/list/list.go
internal/pkg/develop/plugin/create.go
internal/pkg/develop/plugin/validate.go

Add function `pluginExists` to check whether new plugin name is used.

fix: check new plugin name existence for `create-plugin`

---

cmd/devstream/list.go
cmd/devstream/list/list.go

Use `dtm list plugins --filter {regex}` command to filter plugins
issue: #462 #384

feat: dtm list enhancement

---

docs/index.md

docs: update the index page

---

.github/workflows/pr.yml

fix: golang-lint timeout error

fix: golang-lint timeout error

---

cmd/devstream/develop.go
cmd/devstream/list.go
cmd/devstream/options/validator.go
cmd/devstream/show.go
cmd/devstream/validator/validator.go

1. separate args validators and important business code.
2. reduce duplicate code of validators.
#478 
Maybe the place and name of pkg should be changed.

refactor: change ways to validate args

---

docs/plugins/gitlab-repo-scaffolding-golang.md
docs/plugins/plugins-list.md

docs: adding the missing doc for gitlab-repo-scaffolding-golang

docs: adding the missing doc for gitlab-repo-scaffolding-golang

---

internal/pkg/plugin/githubactions/golang/templates.go

github actions workflows need 'write permission', but the repo default config is 'read'.
So we need set it in the workflow to get the permission  while pipelines run

fix: workflow needs write permission

---

docs/core-concepts/core-concepts.md

update code references in core-concetps
> One of the major part of the Config is a list of tools, defined in here
> Each Tool has its Name, Plugin, and Options, as defined here
> The dependency dependsOn is an array of strings, with each element being a dependency. Each dependency is named in the format of "NAME.PLUGIN".
> The State is actually a map of states, as defined here.
> Each state in the map is a struct containing Name, Plugin, Options, and Resource, as defined here.

📖`Docs`: update code references in core-concetps

---

cmd/plugin/argocd/main.go
cmd/plugin/argocdapp/main.go
cmd/plugin/devlake/main.go
cmd/plugin/github-repo-scaffolding-golang/main.go
cmd/plugin/githubactions-golang/main.go
cmd/plugin/githubactions-nodejs/main.go
cmd/plugin/githubactions-python/main.go
cmd/plugin/gitlab-repo-scaffolding-golang/main.go
cmd/plugin/gitlabci-generic/main.go
cmd/plugin/gitlabci-golang/main.go
cmd/plugin/hashicorp-vault/main.go
cmd/plugin/helm-generic/main.go
cmd/plugin/jenkins/main.go
cmd/plugin/jira-github-integ/main.go
cmd/plugin/kube-prometheus/main.go
cmd/plugin/openldap/main.go
cmd/plugin/trello-github-integ/main.go
cmd/plugin/trello/main.go
internal/pkg/develop/plugin/template/main.go

fix: fix go plugin log error

---

docs/commands/develop.md
docs/contributing/creating-a-plugin.md
mkdocs.yml

docs for `develop` command and how does plugin work
close #507 #510

:open_book: `Docs`: `develop` command and how does plugin work

---

go.mod
go.sum
internal/pkg/plugin/argocdapp/options.go
internal/pkg/plugin/argocdapp/validate.go
internal/pkg/plugin/common/reposcaffolding/options.go
internal/pkg/plugin/githubactions/golang/jobs.go
internal/pkg/plugin/githubactions/golang/options.go
internal/pkg/plugin/githubactions/golang/validate.go
internal/pkg/plugin/githubactions/nodejs/options.go
internal/pkg/plugin/githubactions/nodejs/validate.go
internal/pkg/plugin/githubactions/python/options.go
internal/pkg/plugin/githubactions/python/validate.go
internal/pkg/plugin/githubactions/workflow.go
internal/pkg/plugin/gitlabci/generic/options.go
internal/pkg/plugin/gitlabci/generic/validate.go
internal/pkg/plugin/gitlabci/golang/gitlabci.go
internal/pkg/plugin/gitlabci/golang/validate.go
internal/pkg/plugin/jiragithub/options.go
internal/pkg/plugin/jiragithub/validate.go
internal/pkg/plugin/trello/trello.go
internal/pkg/plugin/trello/validate.go
internal/pkg/plugin/trellogithub/validate.go
internal/pkg/plugin/trellogithub/workflow.go
pkg/util/helm/param.go
pkg/util/helm/validation.go
pkg/util/validator/validator.go

#511 
I didn't test every plugin, but I checked them all as much as I could.
Some of the validation rules are too complicated. For example: `githubactions/golang/validate.go` , I kept some of the original validation rules.

refactor: use validator to validate fields

---

cmd/devstream/develop.go
cmd/devstream/list.go
cmd/devstream/main.go
cmd/devstream/show.go

1. modify arguments to subcommand in `dtm list`
2. modify arguments to subcommand in `dtm show`
3. adjust examples information from tab to spaces in `cmd/devstream/develop.go`

refactor: modify args to subcommand in `dtm-list` and `dtm-show`

---

internal/pkg/configloader/config.go
internal/pkg/configloader/variables.go

fix(configloader): fix nil pointer err

---

cmd/devstream/show.go
internal/pkg/show/status/output.go
internal/pkg/show/status/status.go

* Change flag "name" to "id".
* Add "all" flag to `dtm show status` command.
#557

fix: change flag "name" to "id" and add "all" flag

---

cmd/devstream/list/list.go
docs/development/creating-a-plugin.md
internal/pkg/backend/backend.go
internal/pkg/backend/local/local.go
internal/pkg/configloader/validation.go
internal/pkg/configloader/variables.go
internal/pkg/plugin/githubactions/golang/jobs.go
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/outputs.go

In the previous version, varFile was mandatory, but it should actually be optional.

fix(configloader): varFile can be empty

---

internal/pkg/pluginmanager/downloader_test.go

Signed-off-by: KeHao <hao.ke@merico.dev>
Improve the naming of the directory used for unit testing.
Improve the naming of the directory used for unit testing, while retaining the original unit testing directory of s3, so as not to affect users who have not updated their codes in the future.

test: improve the naming of the directory used for unit testing

---

cmd/devstream/apply.go
cmd/devstream/common.go
cmd/devstream/delete.go
cmd/devstream/destroy.go
cmd/devstream/init.go
cmd/devstream/main.go
cmd/devstream/show.go
cmd/devstream/verify.go

Signed-off-by: sjie <sjie>
Delete some global parameters. Some subcommands no longer have global parameters that should not appear
- Fix global parameters displayed on subcommands
- 🍀 Proposal: Some Commands Do Not Need the "-f" Parameter #559

fix: some commands do not need the -f parameter #559

---

test/e2e/yaml/e2e-trello-github-tools.yaml

Signed-off-by: KeHao <hao.ke@merico.dev>
fix:  RepoName -> repoName, the same as it in e2e-variables.yaml

fix: trello-github variable name

---

.github/workflows/e2e-test.yml

Signed-off-by: KeHao <hao.ke@merico.dev>
fix e2e-test :  test workflow on my private repo, main branch. As the below screenshots.

fix:  e2e-test workflow

---

internal/pkg/develop/plugin/template/config.go

The default config already uses `go:embed` to implement ( #614 ), default config is `pluginname.yaml`, and it's in `internal/pkg/show/config/plugins/`, but the `develop create-plugin`  subcommand hasn't updated this part of the code yet
- Generate a default configuration file for the plugin in the `internal/pkg/show/config/plugins/` directory

fix: generate default config file

---

internal/pkg/pluginmanager/manager.go

when there are old development version plugins in `.devstream`, then your change your code, and when you build plugins, they will have a new version number, then executing`dtm init` will report the following error. We need to make sure that only the official release version needs to be downloaded from remote.
```bash
❌ 😭 ./dtm init
2022-05-27 22:03:02 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-05-27 22:03:05 ✖ [ERROR]  [gitlab-repo-scaffolding-golang-darwin-arm64_0.5.0-216-gc6b4aba.so] download failed, 403 Forbidden.
2022-05-27 22:03:05 ✖ [ERROR]  Remove [.devstream/gitlab-repo-scaffolding-golang-darwin-arm64_0.5.0-216-gc6b4aba.so.tmp] failed, remove .devstream/gitlab-repo-scaffolding-golang-darwin-arm64_0.5.0-216-gc6b4aba.so.tmp: no such file or directory.
2022-05-27 …
```

fix: avoid downloading development version plugins from remote

---

.editorconfig

optimize `.edtirconfig`
Closes [#634 ](https://github.com/devstream-io/devstream/issues/634)

chore: optimize editorconfig

---

.golangci.yml
Makefile

- Integrate the `golangci-lint` command in the makefile, so that we can use it to test code quality in local
- Add `golangci-lint` config file, maybe we can add more rules in this file in the future
#632 
``` bash
✅ 😁 make lint 
Run golangci to lint source codes
```

chore: add golangci-lint config

---

cmd/devstream/develop.go
cmd/devstream/list/list.go
internal/pkg/configloader/config.go
internal/pkg/configloader/validation.go
internal/pkg/develop/plugin/create.go
internal/pkg/develop/plugin/plugin.go
internal/pkg/develop/plugin/validate.go
internal/pkg/pluginengine/change.go
internal/pkg/pluginengine/change_helper.go
internal/pkg/pluginengine/outputs.go
internal/pkg/pluginengine/topological_sort.go
internal/pkg/pluginmanager/manager.go
internal/pkg/statemanager/manager.go

1. accurate some code comments.
2. fix some log errors, spelling errors.
3. minor code changes.

chore: accurate code comments and minor code changes

---

cmd/devstream/apply.go
cmd/devstream/completion.go
cmd/devstream/delete.go
cmd/devstream/destroy.go
cmd/devstream/init.go
cmd/devstream/main.go
cmd/devstream/show.go
cmd/devstream/verify.go
internal/pkg/completion/completion.go

Signed-off-by: prodan <pengshihaoren@gmail.com>
Auto-completion help, take `bash` as an example
```
$ ./dtm completion bash -h
generate autocompletion script for bash
Usage:
dtm completion bash [flags]
Examples:
Load is completions in the current shell session:
load completions for every new session:
(in Linux)# dtm completion bash > /etc/bash_completion.d/dtm
(in MacOS)# dtm completion bash > /usr/local/etc/bash_completion.d/dtm
Flags:
-h, --help   help for bash
Global Flags:
--debug   debug level log
```
1、`Flags` autocomplete
```bash
prodan@ubuntu:~/Desktop$ ./dtm show [TAB][TAB]
config  status  
prodan@ubuntu:~/Desktop$ ./dtm show config -[TAB][TAB]
--debug    -p         --plugin   --plugin=  
prodan@ubuntu:~/Desktop$ …
```

feat: add command completion

---

cmd/plugin/tekton/main.go
docs/plugins/tekton.md
internal/pkg/plugin/common/helm/helm.go
internal/pkg/plugin/tekton/create.go
internal/pkg/plugin/tekton/delete.go
internal/pkg/plugin/tekton/read.go
internal/pkg/plugin/tekton/state.go
internal/pkg/plugin/tekton/tekton.go
internal/pkg/plugin/tekton/update.go
internal/pkg/plugin/tekton/validate.go
internal/pkg/show/config/plugins/tekton.yaml
internal/pkg/show/status/status.go

Support tekton plugin installed using helm.
- new plugin: tekton
- it takes three option inputs: chart, repo and create_namespace
- it get helm template from repo and install tekton using chart variable
- docs are also updated
- added to dtm show as well

feat: new plugin - tekton 

---

mkdocs.yml

- fixed an issue where the search bar isn't available if the "latest" version is selected
- fixed an issue where the language selector isn't available when a specific page (non-index page) is selected
Screenshot:

chore: fix language selector and search bar

---

docs/contributing_guide.md
docs/development/good-first-issues.md
docs/development/good-first-issues.zh.md
mkdocs.yml

A new doc for good first issues.
@aFlyBird0 please work on the Chinese version of it.

docs: good first issue doc english

---

docs/development/mkdocs.zh.md

Signed-off-by: dingweiwei <dingweiwei@admin.com>

docs:mkdocs.md doc chinese version

---

Makefile
hack/githooks/commit-msg

Signed-off-by: xuwu <ixw1991@126.com>
- The hook is triggered when the user submits a commit, detecting whether the commit message conforms to the specification, and if not, outputting a help message
- Automatic signature
- Automatically copy git hooks when executing `make`
#749 
```bash
xx:code bing$ uname -smp
Darwin x86_64 i386
xx:code bing$ git commit -m "justfortest"
Error! The commit message should be structured as follows:
<type>[optional scope]: <description>
[optional body]
[optional footer(s)]
where "type" can be: feat fix doc docs chore ci build perf style revert test
For details, please refer to https://www.conventionalcommits.org/en/v1.0.0/#summary
xx:code bing$ git commit -m "test: test"
[master (root-commit) …
```

chore: add commit msg git hook

---

docs/development/mkdocs.zh.md

Signed-off-by: “amdaous <dreamlife1991@163.com>
Translate “Setting up Navigation” section in the docs/development/mkdocs.md
#742

docs: mkdocs.zh.md

---

cmd/devstream/apply.go
cmd/devstream/common.go
cmd/devstream/delete.go
cmd/devstream/destroy.go
cmd/devstream/init.go
cmd/devstream/list.go
cmd/devstream/verify.go
internal/pkg/completion/completion.go

- Support filter file completion
- Support filter dir completion
Closes #753

chore: completion enhancement

---

docs/development/build.zh.md
docs/development/lint.zh.md

docs: build.zh.md, lint.zh.md chinese version, issue 710

---

.gitignore
hack/e2e/e2e-run.sh
test/e2e/suites.go
test/e2e/yaml/e2e-test-local.yaml

Changes:
- update gitignore to include temporary yaml files
- remove dead code
- change dockerhub username in the template
- update timeout, update default app name, fix pod readiness check bug
- rename functions
- improve logging

test: improve the robustness of e2e test local execution

---

docs/development/test.md

docs: e2e test doc update

---

docs/core-concepts/config.md
docs/core-concepts/stateconfig.md
mkdocs.yml

Closes https://github.com/devstream-io/devstream/issues/762

docs: update structure and add more doc on s3 backend

---

.github/workflows/license-scan.yml

license scanning for CNCF compliance
The corresponding triggered scan actions are here:  https://github.com/devstream-io/devstream/runs/7077653652?check_suite_focus=true

ci: license scanning for cncf compliance

---

docs/quickstart.zh.md
hack/quick-start/quickstart.sh

Create a one-click script for quick start. Execute these steps in one script:
1. Download latest dtm release according to OS and CPU arch.
2. Rename release to "dtm".
3. Download quickstart.yaml.
4. Show dtm help.
close #769 
on macOS:
❯ sh quickstart.sh
```shell
Got OS type: darwin and CPU arch: arm64
Latest dtm release version: v0.7.0
Downloading dtm from: https://devstream.gateway.scarf.sh/releases/v0.7.0/dtm-darwin-arm64
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
0     0    0     0    0     0      0      0 --:--:--  0:00:01 …
```

feat: create a one-click script for quick start

---

docs/development/test.zh.md

docs: create test.zh.md

---

.github/workflows/license-scan.yml

Use variables  in GitHub config, not hard code in workflow file

ci: referencing variables using github config

---

docs/best-practices/gitops.md
docs/plugins/jenkins.md
docs/plugins/jenkins.zh.md
internal/pkg/plugin/jenkins/create.go
internal/pkg/plugin/jenkins/delete.go
internal/pkg/plugin/jenkins/jenkins_suite_test.go
internal/pkg/plugin/jenkins/options.go
internal/pkg/plugin/jenkins/precreate.go
internal/pkg/plugin/jenkins/prompt.go
internal/pkg/plugin/jenkins/read.go
internal/pkg/plugin/jenkins/update.go
internal/pkg/plugin/jenkins/validate.go
internal/pkg/plugin/jenkins/validate_test.go
internal/pkg/show/config/plugins/jenkins.yaml

1. support test mod and prod mode meanwhile.
* test: auto-create PV named `jenkins-pv` and use host path
* prod: user can customize `storageClass`
2. use NodePort to expose service.
3. support `nodePort` config customize.
4. show Jenkins URL and tell user how to get the password of user admin
5. docs improved.
#758 
./dtm apply -f jenkins.yaml -y
2022-06-27 20:48:26 ℹ [INFO]  Apply started.
2022-06-27 20:48:26 ℹ [INFO]  Got Backend from config: local
2022-06-27 20:48:26 ℹ [INFO]  Using dir <.devstream> to store plugins.
2022-06-27 20:48:27 ℹ [INFO]  Using local backend. State file: devstream.state.
2022-06-27 20:48:27 ℹ [INFO]  Tool (jenkins/default) found in config but doesn't exist in the state, will be created. …

feat: `jenkins` plugin prod ready

---

docs/plugins/jenkins.md
docs/plugins/jenkins.zh.md

Update Jenkins plugin's documentation according to the latest change, both English and Chinese.

docs: update jenkins plugin doc

---

internal/pkg/plugin/argocd/validate.go
internal/pkg/plugin/hashicorpvault/validate.go
internal/pkg/plugin/helmgeneric/validate.go
internal/pkg/plugin/jenkins/validate.go
internal/pkg/plugin/kubeprometheus/validate.go
internal/pkg/plugin/openldap/validate.go
internal/pkg/plugin/tekton/validate.go
pkg/util/helm/validation.go

chore(refactor): refactor helm validate and set default timeout.

---

.github/workflows/link-pr.yml
.github/workflows/link.yml
.lycheeignore

* When/How to trigger
* 8:30 every day
* markdown file being changed during pr
* Scope
* MkDocs generated sites
* markdown files in the root of the project
* Steps
1. local build MkDocs
2. Use [lychee-action](https://github.com/lycheeverse/lychee-action) to perform the check
* Next actions: 
* goto GitHub Actions to see detailed errors. 
* If there are broken links, the issue will be automatically sent and the specified document owner will be assigned if there are broken links (currently not enabled, wait for all existing broken links to be fixed before enabling).
close #792 
example: https://github.com/aFlyBird0/devstream-fork/actions/runs/2590054005
A screenshot of the example above:

feat(ci): add broken links check CI

---

internal/pkg/configloader/config.go

Improving The Robustness of Config File
- judge core config by key `core`
- judge tool config by key `tools`
https://github.com/devstream-io/devstream/issues/659

feat: Improving The Robustness of Config File

---

docs/development/help-wanted.md
mkdocs.yml

Created new documentation on how to create/groom issues for the help wanted label.
@aFlyBird0 you can prepare the Chinese version now.

docs: create a doc for the help wanted label

---

docs/core-concepts/core-concepts.md

Signed-off-by: Prajwal Borkar <prajwalborkar5075@gmail.com>
Fixed typo in `core-concepts.md` file
Fixes #778

Fixed typo

---

OWNERS

After a private members meeting, we decide to promote @algobot76 as a reviewer.
According to our [reviewer definition](https://docs.devstream.io/en/latest/contributor_ladder/#reviewer), the responsibilities of a reviewer are the following:
- Following the reviewing guide
- Reviewing most Pull Requests against their specific areas of responsibility
- Reviewing at least 20 PRs per year
- Helping other contributors become reviewers
And, the requirements of a reviewer are:
- Experience as a Contributor for at least 1 months
- Is an Organization Member
- Has reviewed, or helped review, at least 5 Pull Requests
- Has analyzed and resolved test failures in their specific area
- Has demonstrated an in-depth knowledge of the specific area
- Commits to being responsible for that specific area
- Is …

Proposing a new reviewer: @algobot76

---

hack/githooks/commit-msg

Add `refactor` type to githooks
close #831

fix: add refactor type to githooks

---

pkg/util/validator/validator_test.go

What problems it tries to solve:
- add ut
- ut coverage:
```sh
[going@dev validator]$ go test . -coverprofile=./coverage.out -timeout=10m -short -v
=== RUN   TestStruct
=== RUN   TestStruct/base
=== RUN   TestStruct/base_Tool_instance
--- PASS: TestStruct (0.00s)
--- PASS: TestStruct/base (0.00s)
--- PASS: TestStruct/base_Tool_instance (0.00s)
=== RUN   Test_dns1123SubDomain
=== RUN   Test_dns1123SubDomain/base
=== RUN   Test_dns1123SubDomain/base#01
--- PASS: Test_dns1123SubDomain (0.00s)
--- PASS: Test_dns1123SubDomain/base (0.00s)
--- PASS: Test_dns1123SubDomain/base#01 (0.00s)
PASS
coverage: 90.0% of …
```

feat: pkg-util-validator Enhancement

---

pkg/util/md5/helper_test.go
pkg/util/md5/md5_test.go

Maybe there is an OOM risk in this code, so try to fix it.
- add an defer for closing the file:
- add a ut for the  funcion:
```sh
[going@dev md5]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/md5/helper.go:11:    CalcFileMD5     90.0%
github.com/devstream-io/devstream/pkg/util/md5/md5.go:12:       FileMatchesMD5  75.0%
total:                                                          (statements)    83.3%
```

🍀 Proposal: pkg/util/md5 Enhancement (sub task of pkg/util Enhancement #833)

---

pkg/util/kubectl/cmd.go
pkg/util/kubectl/cmd_test.go

- try to add ut for the package
```sh
[going@dev kubectl]$ go test -race -cover  -coverprofile=./coverage.out -timeout=10m -short -v
=== RUN   TestKubeCreate
=== RUN   TestKubeCreate/base
2022-07-18 09:04:50 !! [ERROR]  Failed to exec: < /usr/local/bin/kubectl create -f nginx-deployment.yaml >.
2022-07-18 09:04:50 !! [ERROR]  Exec logs: < The connection to the server localhost:8080 was refused - did you specify the right host or port?
>. Got error: exit status 1.
--- PASS: TestKubeCreate (0.07s)
--- PASS: TestKubeCreate/base (0.07s)
=== RUN   TestKubeApply
=== RUN   TestKubeApply/base
2022-07-18 09:04:50 …
```

feat: pkg-util-kubectl Enhancement

---

pkg/util/downloader/downloader.go
pkg/util/downloader/downloader_test.go

trying to resolve:
- OOM risk
- adding url's empty check to make the fail fast
- add more test case to increase the test coverage
- the OOM risk is here
- ut coverage hit 100%
```sh
[going@dev downloader]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/downloader/downloader.go:12: Download        100.0%
total:                                                                  (statements)    100.0%
```

feat: pkg/uil/downloader Enhancement

---

cmd/devstream/completion.go
go.mod
go.sum

Signed-off-by: xuwu <ixw1991@126.com>
- generate Fig completion spec by using `dtm completion fig` (Because it's used to push to https://github.com/withfig/autocomplete, our user don't need to know it so the cmd is hidden)
#627

feat: add fig completion spec generate

---

.github/workflows/e2e-test.yml

let the concurrency of e2e workflow be 1.
Otherwise, if the concurrency of the workflow will be greater than 1, resulting in e.g. a GitHub repo just being deleted and created again, this will cause the previous workflow to fail in the cleanup step.
As you can see from the screenshot below from a test on my personal repository, two e2e actions were triggered by consecutive commits, but one of the later actions was pended

ci: let the concurrency of e2e workflow be 1

---

cmd/devstream/show.go
internal/pkg/show/config/config.go

I remove the default value of `template`. We can discuss better solution.
close #841

fix: show non-existent plugin config

---

internal/pkg/pluginengine/change_helper.go

Signed-off-by: homily707 <homily707@outlook.com>
replace for loop with map in topologicalSortChangesInBatch
no

refactor: replace for loop with map in topologicalSortChangesInBatch

---

hack/e2e/e2e-run.sh
test/e2e/yaml/e2e-test-local.yaml

Signed-off-by: hxcGit <houxc_mail@163.com>
fix e2e script: terminate e2e test when encounter errors
#873

fix: stop e2e test when encounter errors

---

go.mod
pkg/util/gitlab/ci_yml_templates_test.go
pkg/util/gitlab/commits.go
pkg/util/gitlab/commits_test.go
pkg/util/gitlab/gitlab.go
pkg/util/gitlab/gitlab_test.go
pkg/util/gitlab/project_test.go
pkg/util/gitlab/repository_files.go
pkg/util/gitlab/repository_files_test.go

add ut for the package
```sh
[going@dev gitlab]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/gitlab/ci_yml_templates.go:6:        GetGitLabCIGolangTemplate       75.0%
github.com/devstream-io/devstream/pkg/util/gitlab/commits.go:14:                CommitSingleFile                83.3%
github.com/devstream-io/devstream/pkg/util/gitlab/commits.go:35:                DeleteSingleFile                83.3%
github.com/devstream-io/devstream/pkg/util/gitlab/commits.go:55:                UpdateSingleFile                83.3%
github.com/devstream-io/devstream/pkg/util/gitlab/commits.go:76:                CommitMultipleFiles …
```

feat: pkg/util/gitlab Enhancement (sub task of pkg/util Enhancement #833) 

---

pkg/util/github/branch_test.go
pkg/util/github/github_test.go
pkg/util/github/release_test.go

add ut for pkg/util/github/branch
```sh
[going@dev github]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/github/branch.go:11:                 NewBranch                               100.0%
github.com/devstream-io/devstream/pkg/util/github/branch.go:38:                 DeleteBranch                            100.0%
github.com/devstream-io/devstream/pkg/util/github/commit.go:11:                 GetLastCommit                           0.0%
```

feat: pkg/util/github/branch enhancement

---

cmd/plugin/artifactory/main.go
docs/plugins/artifactory.md
docs/plugins/artifactory.zh.md
internal/pkg/plugin/artifactory/artifactory.go
internal/pkg/plugin/artifactory/create.go
internal/pkg/plugin/artifactory/delete.go
internal/pkg/plugin/artifactory/read.go
internal/pkg/plugin/artifactory/update.go
internal/pkg/show/config/embed_gen.go
internal/pkg/show/config/plugins/artifactory.yaml

- create artifactory service
close #607

feat: add artifactory plugin

---

pkg/util/github/branch_test.go
pkg/util/github/commit_test.go
pkg/util/github/download_test.go
pkg/util/github/file_test.go
pkg/util/github/github_suite_test.go
pkg/util/github/github_test.go
pkg/util/github/pullrequest.go
pkg/util/github/pullrequest_test.go
pkg/util/github/release_test.go
pkg/util/github/secrets_test.go

add ut for secrets
```sh
[going@dev github]$ go tool cover -func=coverage.out
...
github.com/devstream-io/devstream/pkg/util/github/secrets.go:14:                AddRepoSecret                           92.3%
github.com/devstream-io/devstream/pkg/util/github/secrets.go:44:                encryptSecretWithPublicKey              84.6%
github.com/devstream-io/devstream/pkg/util/github/secrets.go:76:                DeleteRepoSecret                        90.0%
github.com/devstream-io/devstream/pkg/util/github/secrets.go:95:                RepoSecretExists                        90.0%
...
total: …
```

feat: pkg/util/github/secrets

---

pkg/util/github/download_test.go
pkg/util/github/github_suite_test.go
pkg/util/github/github_test.go
pkg/util/github/pullrequest_test.go
pkg/util/github/repo.go
pkg/util/github/repo_test.go
pkg/util/github/secrets_test.go

add ut for repo
```sh
[going@dev github]$ go tool cover -func=coverage.out
github.com/devstream-io/devstream/pkg/util/github/repo.go:12:                   CreateRepo                              100.0%
github.com/devstream-io/devstream/pkg/util/github/repo.go:28:                   DeleteRepo                              100.0%
github.com/devstream-io/devstream/pkg/util/github/repo.go:51:                   GetRepoDescription                      81.8%
github.com/devstream-io/devstream/pkg/util/github/repo.go:79:                   PushLocalPathToBranch                   26.7% …
```

feat: pkg-util-github-repo enhancement

---

pkg/util/github/download_test.go

Note: Please complete **_ALL_** items in the following checklist.
add ut for download
github.com/devstream-io/devstream/pkg/util/github/download.go:14:               DownloadAsset                           100.0%
github.com/devstream-io/devstream/pkg/util/github/download.go:83:               DownloadLatestCodeAsZipFile             100.0%

feat:pkg/util/gitHub/download enhancement

---

pkg/util/github/pullrequest_test.go
pkg/util/github/repo_test.go

feat: pkg-util-github-pullrequest enhancement

---

.github/ISSUE_TEMPLATE/documentation.yaml

Fix issue template error with documentation type
N/A
Old behavior: 
The document list don't be shown at the issue page.

fix: issue template error with documentation type

---

.gitignore
.lycheeignore
docs/plugins/gitlab-ce-docker.md
docs/plugins/gitlab-ce-docker.zh.md

gitlab-ce-docker docs enhancement
N/A
N/A

docs: gitlab-ce-docker docs enhancement

---

.github/workflows/link-pr.yml
.lycheeignore

Solved the problem where the `.lycheeignore` file was modified during pr but did not take effect immediately.
`checkout` actions will pull the newest code so there is no need to download files again.

ci: use `.lycheeignore` in current pr rather than `main` branch

---

docs/plugins/argocd.md
internal/pkg/plugin/argocd/argocd.go
internal/pkg/plugin/argocd/create.go
internal/pkg/plugin/argocd/delete.go
internal/pkg/plugin/argocd/read.go
internal/pkg/plugin/argocd/update.go
internal/pkg/plugininstaller/helm/helm_suit_test.go
internal/pkg/plugininstaller/helm/option.go
internal/pkg/plugininstaller/helm/option_test.go
internal/pkg/plugininstaller/helm/validate.go
internal/pkg/plugininstaller/helm/validate_test.go
pkg/util/helm/helm.go
pkg/util/helm/helm_operation_test.go
pkg/util/helm/helm_test.go
pkg/util/helm/param.go
pkg/util/helm/validation.go
pkg/util/helm/validation_test.go
pkg/util/types/bool.go

- plugin `argocd` support default value config
- add unit test for helm installer
- all helm options add `mapstructure` field name
- helm validate func not execute default logic
#514

feat: support helm plugin default value

---

docs/plugins/gitlab-ce-docker.md
docs/plugins/gitlab-ce-docker.zh.md
internal/pkg/plugin/gitlabcedocker/create.go
internal/pkg/plugin/gitlabcedocker/delete.go
internal/pkg/plugin/gitlabcedocker/gitlabcedocker.go
internal/pkg/plugin/gitlabcedocker/options.go
internal/pkg/plugin/gitlabcedocker/options_test.go
internal/pkg/plugin/gitlabcedocker/read.go
internal/pkg/plugin/gitlabcedocker/update.go
internal/pkg/plugin/gitlabcedocker/validate.go
internal/pkg/plugininstaller/docker/installer.go
internal/pkg/plugininstaller/docker/option.go
internal/pkg/show/config/plugins/gitlab-ce-docker.yaml

The Plugin GitLab CE Enhancement - Existing logic optimization.
I will refactor the Read() and Update() functions in the next pr.
@IronCore864 @aFlyBird0 PTAL.
N/A
- `config-gitlab.yaml` (ssh_port is set to avoid "address already in use" error)
```yaml
---
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
state: # state config, backend can be local or s3
backend: local
options:
---
tools:
- name: gitlab-ce-docker
dependsOn: [ ]
options:
ssh_port: 2022
```
- `./dtm apply -f config-gitlab.yaml`
```sh
2022-08-07 11:08:58 ℹ [INFO]  Apply …
```

Feat: The Plugin GitLab CE Enhancement

---

pkg/util/github/repo.go
pkg/util/github/repo_test.go

Signed-off-by: csonezp <csonezp@gmail.com>
repo-scaffolding should protect the default main branch.
I'm not used to using ginkgo, so the test cases may not be well designed, If you find any problem please submit some suggestions
Closes #963 
When use repo-scaffolding to create destination repo, protected the default branch.

feat: protect branch when init github repo

---

.github/workflows/automated-release.yml
.github/workflows/e2e-test.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/update-fig-spec.yml

`actions/setup-go@v3` has a built-in caching, and I noticed that the current `pr.yml` cache is useless. I replaced them with a simpler form.
https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
close #981

fix: workflows go mod cache

---

pkg/util/helm/param.go
pkg/util/validator/validator.go
pkg/util/validator/validator_test.go

Writing yaml string is very easy to cause syntax errors due to the lack of IDE support, and I add yaml syntax validation for validator package.
close #977 
bad `values_yaml`:
good `values_yaml`:

feat: add yaml validation for validator

---

internal/pkg/plugin/jenkins/create.go
internal/pkg/plugin/jenkins/delete.go
internal/pkg/plugin/jenkins/jenkins.go
internal/pkg/plugin/jenkins/options.go
internal/pkg/plugin/jenkins/read.go
internal/pkg/plugin/jenkins/update.go
internal/pkg/plugininstaller/helm/option.go
internal/pkg/plugininstaller/helm/validate.go

fix: jenkins' `test_env` options was overridden

---

pkg/util/git/commit_test.go

The latest version of golangci-lint checks for deprecated `ioutil` 
A file change was missed in #970
```
pkg/util/git/commit_test.go:4:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and t
hose implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
```
N/A

fix: change ioutil to os

---

docs/plugins/harbor.md

English doc for Harbor.
It's _NOT_ a translation of the Chinese version of the documentation; multiple sections are not included.

docs: English doc for the harbor plugin

---

internal/pkg/plugin/jenkins/options.go
internal/pkg/plugin/jenkins/prompt.go

close #1008 
tool file: as same as tool file in #1008

fix: error during `showJenkinsUrl`

---

cmd/devstream/apply.go
cmd/devstream/delete.go
cmd/devstream/init.go
cmd/devstream/show.go
cmd/devstream/verify.go
docs/core-concepts/config.md
docs/core-concepts/config.zh.md
docs/core-concepts/core-concepts.md
docs/core-concepts/core-concepts.zh.md
docs/core-concepts/stateconfig.md
docs/plugins/zentao.md
docs/plugins/zentao.zh.md
examples/gitops.yaml
examples/quickstart.yaml
go.mod
go.sum
internal/pkg/configmanager/configmanager.go
internal/pkg/configmanager/coreconfig.go
internal/pkg/pluginengine/cmd_apply.go
internal/pkg/pluginengine/cmd_delete.go
internal/pkg/pluginengine/cmd_destroy.go
internal/pkg/pluginengine/cmd_verify.go
internal/pkg/pluginengine/plugin.go
internal/pkg/pluginengine/plugin_helper.go
internal/pkg/pluginmanager/manager.go
internal/pkg/show/status/status.go
pkg/util/file/file.go

A simpler solution to the plugin absolute path problem that does not affect documentation.
The only impact is that the developer needs to specify `-d .devstream` when debugging the plugin.
close #997 
The plugin version shown is for demonstration purposes only, not the actual situation.

feat!: change default plugin dir

---

.lycheeignore
docs/plugins/jenkins.zh.md
internal/pkg/plugin/argocdapp/state.go
internal/pkg/plugin/devlake/state.go
internal/pkg/plugin/helmgeneric/state.go
internal/pkg/plugin/jenkins/create.go
internal/pkg/plugin/jenkins/jenkins.go
internal/pkg/plugin/jenkins/read.go
internal/pkg/plugin/jenkins/update.go
internal/pkg/plugin/trello/trello.go
internal/pkg/pluginengine/pluginengine_test.go
internal/pkg/plugininstaller/ci/state.go
internal/pkg/plugininstaller/common/state.go
internal/pkg/plugininstaller/docker/compose.go
internal/pkg/plugininstaller/docker/state.go
internal/pkg/plugininstaller/github/state.go
internal/pkg/plugininstaller/goclient/installer.go
internal/pkg/plugininstaller/helm/state.go
internal/pkg/plugininstaller/plugininstaller.go
internal/pkg/plugininstaller/reposcaffolding/state.go
internal/pkg/statemanager/state.go

1. `jenkins` plugin state management enhancement;
2. add `outputs` to `jenkins` plugin;
3. unify the way "outputs" are set up of all plugins;
4. docs updated.
#993
- config `config-jenkins.yaml`
```yaml
---
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
pluginDir: ".devstream"
state: # state config, backend can be local or s3
backend: local
options:
---
tools:
- name: jenkins
dependsOn: [ ]
options:
chart:
values_yaml: |
serviceAccount:
create: true
name: jenkins
controller:
adminUser: "admin"
ingress:
enabled: true
hostName: jenkins.example.com
```
- apply once `./dtm apply …

Feat: `jenkins` plugin State Management Enhancement

---

cmd/devstream/init.go
internal/pkg/pluginengine/cmd_apply.go
internal/pkg/pluginengine/cmd_delete.go
internal/pkg/pluginengine/cmd_destroy.go
internal/pkg/pluginengine/cmd_verify.go
internal/pkg/show/status/status.go
pkg/util/file/file.go

fix plugin directory render error when "~" used in the config.
I've tested this pr locally.
config:
```yaml
...
pluginDir: "~/.devstream/plugins"
...
```
logs:
```sh
2022-09-01 14:28:18 ℹ [INFO]  Delete started.
2022-09-01 14:28:18 ℹ [INFO]  Using dir <~/.devstream/plugins> to store plugins.
2022-09-01 14:28:18 !! [ERROR]  Error checking required plugins. Maybe you forgot to run "dtm init" first?
2022-09-01 14:28:18 !! [ERROR]  Delete error: plugin jenkins doesn't exist.
```
```sh
...
2022-09-01 15:03:17 ✔ [SUCCESS]  Tool (jenkins/default) delete done.
2022-09-01 15:03:17 λ [DEBUG]  End -> StatesMap now is:
2022-09-01 15:03:17 ℹ [INFO]  -------------------- [  Processing done.  ] …
```

fix: plugin directory render error when "~" used in the config

---

internal/pkg/plugin/gitlabcedocker/update.go

fix gitlab-ce-docker update failed
fix #1042 
- `./dtm apply -f config-gitlab-jenkins-harbor-java.yaml `
```sh                                                                                      
2022-09-01 16:56:29 ℹ [INFO]  Apply started.
2022-09-01 16:56:29 ℹ [INFO]  Using dir </Users/danielhu/.devstream/plugins> to store plugins.
2022-09-01 16:56:29 ℹ [INFO]  Using local backend. State file: devstream.state.
2022-09-01 16:56:29 ℹ [INFO]  Tool (gitlab-ce-docker/default) config drifted from the state, will be updated.
2022-09-01 16:56:32 ℹ [INFO]  Start executing the plan.
2022-09-01 16:56:32 ℹ [INFO]  Changes count: 1. …
```

fix: gitlab-ce-docker update failed

---

internal/pkg/plugininstaller/ci/option.go
internal/pkg/plugininstaller/jenkins/option.go
internal/pkg/plugininstaller/jenkins/option_test.go
internal/pkg/plugininstaller/jenkins/validate.go
internal/pkg/plugininstaller/jenkins/validate_test.go
pkg/util/scm/gitlab/commit.go
pkg/util/scm/gitlab/errors.go
pkg/util/scm/gitlab/file.go
pkg/util/scm/gitlab/repo.go
staging/dtm-jenkins-pipeline-example/springboot/Jenkinsfile

- `jenkins-pipeline` plugin support `Harbor` variable
- fix `Gitlab` silent error
#993

feat: jenkins pipeline support image repo variable

---

pkg/util/scm/gitlab/repo.go
staging/dtm-repo-scaffolding-java-springboot/.gitignore
staging/dtm-repo-scaffolding-java-springboot/README.md.tpl

- gitlab webhook support merge request event
- spring repo-scaffolding add Readme
#993

feat: jenkins-gitlab support push merge request event

---

hack/release/auto-release-darwin-arm64.sh

make clean before make build, to avoid uploading old files

fix: clean before build, to avoid uploading old files

---

.github/workflows/automated-release.yml

fix auto release plugins dir error

fix: auto release plugins dir error

---

cmd/plugin/sonarqube/main.go
docs/plugins/sonarqube.md
docs/plugins/sonarqube.zh.md
internal/pkg/plugin/sonarqube/create.go
internal/pkg/plugin/sonarqube/delete.go
internal/pkg/plugin/sonarqube/read.go
internal/pkg/plugin/sonarqube/sonar.go
internal/pkg/plugin/sonarqube/update.go
internal/pkg/show/config/embed_gen.go
internal/pkg/show/config/plugins/sonarqube.yaml

- Add plugin `Sonarqube`.
- Add plugin `Sonarqube` chinese docs.
#993 
#639

feat: add plugin sonar

---

cmd/devstream/init.go
cmd/devstream/list/list.go
docs/commands/init.md
internal/pkg/configmanager/configmanager.go
internal/pkg/pluginmanager/manager.go
internal/pkg/pluginmanager/manager_test.go
pkg/util/file/file.go

1. use `dtm init --download-only` to download specify plugins from flags.
2. use `--plugins` to specify plugins to download.
3. use `--all` to download all plugins.
4. use `--os` and `--arch` to specify os and arch, the default is os and arch of the machine which executes dtm.
The first task of #1084.
(We can use quick-start script to download `dtm` and use `dtm init --all --os=DestinyOS --arch=DestinyArch -d=PLUGIN_DIR` to download plugins.
Comment out this code and test:

feat: use `dtm init --download-only` to download specify plugins from flags

---

cmd/devstream/destroy.go
cmd/devstream/develop.go
docs/commands/apply.md
docs/commands/apply.zh.md
docs/commands/delete.md
docs/commands/delete.zh.md
docs/commands/destroy.md
docs/commands/destroy.zh.md
docs/commands/init.md
docs/commands/init.zh.md
docs/commands/verify.md
docs/commands/verify.zh.md
docs/plugins/harbor.zh.md
docs/plugins/jenkins.zh.md

1. Add `flags` part to all docs blow `command` part
2. Translate apply/init/delete/destroy/verify into Chinese
3. Update `init.md`
#862

doc: add flags to docs of `command` part and translate some docs

---

docs/best-practices/gitlab-jenkins-harbor.zh.md
docs/plugins/jenkins-pipeline.zh.md
internal/pkg/plugininstaller/common/repo.go
internal/pkg/plugininstaller/common/repo_test.go
internal/pkg/plugininstaller/jenkins/installer.go
internal/pkg/plugininstaller/jenkins/option.go
internal/pkg/plugininstaller/jenkins/option_test.go
internal/pkg/plugininstaller/jenkins/validate.go
internal/pkg/plugininstaller/jenkins/validate_test.go
internal/pkg/show/config/plugins/jenkins-pipeline.yaml
pkg/util/jenkins/auth.go
pkg/util/jenkins/jenkins.go
pkg/util/jenkins/tpl/seedjob.tpl.groovy
pkg/util/scm/client.go
pkg/util/scm/gitlab/gitlab.go

- `Jenkins` support clone private repo
- delete `scm.projectRepo` and `scm.projectBranch` field
- add `scm.cloneURL` for clone config, `scm.apiURL` for api request, `scm.branch` for repo branch config
- add `GITLAB_SSHKEY` environment variable for private repo
#993 
- create `Jenkins` credential for private key
- create job with this credential

feat: Jenkins repo support private repo

---

docs/best-practices/gitlab-jenkins-harbor.zh.md

gitlab-jenkins-harbor.zh.md title fixed
N/A
document updated only

docs: gitlab-jenkins-harbor.zh.md title fixed

---

internal/pkg/upgrade/upgrade.go

Related to #1110 ,change some code to support get binary file name when execute upgrade command.
#1110
no

feat: Support automatically detect binary filenames on dtm upgrade

---

internal/pkg/show/config/plugins/argocd.yaml
internal/pkg/show/config/plugins/argocdapp.yaml
internal/pkg/show/config/plugins/artifactory.yaml
internal/pkg/show/config/plugins/githubactions-golang.yaml
internal/pkg/show/config/plugins/githubactions-nodejs.yaml
internal/pkg/show/config/plugins/githubactions-python.yaml
internal/pkg/show/config/plugins/gitlabci-generic.yaml
internal/pkg/show/config/plugins/gitlabci-golang.yaml
internal/pkg/show/config/plugins/harbor.yaml
internal/pkg/show/config/plugins/hashicorp-vault.yaml
internal/pkg/show/config/plugins/helm-generic.yaml
internal/pkg/show/config/plugins/jenkins.yaml
internal/pkg/show/config/plugins/jira-github-integ.yaml
internal/pkg/show/config/plugins/kube-prometheus.yaml
internal/pkg/show/config/plugins/openldap.yaml
internal/pkg/show/config/plugins/sonarqube.yaml
internal/pkg/show/config/plugins/tekton.yaml
internal/pkg/show/config/plugins/trello-github-integ.yaml
internal/pkg/show/config/plugins/trello.yaml
internal/pkg/show/config/plugins/zentao.yaml

1. add chart.version field
2. unify the indentation style
N/A
N/A

Chore: Add `chart.version` Field And Unify the Indentation Style of the Config Files

---

docs/best-practices/gitops.zh.md
docs/development/commit-messages.zh.md
docs/development/creating-a-plugin.zh.md
docs/development/project-layout.zh.md
docs/quickstart.zh.md

docs: replace all English links in Chinese documents with Chinese links

---

internal/pkg/plugin/gitlabci/java/create.go
internal/pkg/plugininstaller/ci/ci.go
internal/pkg/plugininstaller/ci/githubci.go
internal/pkg/plugininstaller/ci/gitlabci.go
internal/pkg/plugininstaller/ci/installer.go
internal/pkg/plugininstaller/ci/jenkinsci.go
internal/pkg/plugininstaller/ci/option.go
internal/pkg/plugininstaller/ci/state.go
internal/pkg/plugininstaller/ci/utils.go
internal/pkg/plugininstaller/ci/utils_test.go
pkg/util/file/dir.go
pkg/util/scm/client.go
pkg/util/scm/client_test.go
pkg/util/scm/git/commit.go
pkg/util/scm/git/commit_test.go
pkg/util/scm/git/repoinfo.go
pkg/util/scm/git/state.go
pkg/util/scm/git/state_test.go
pkg/util/scm/github/commit.go
pkg/util/scm/github/file.go
pkg/util/scm/github/repo.go
pkg/util/scm/github/repo_test.go
pkg/util/scm/gitlab/commit.go
pkg/util/scm/gitlab/commit_test.go
pkg/util/scm/gitlab/file.go

1. fix some typo
2. refactor `/internal/plugininstaller/ci`

refactor: some refactors and fix some typo

---

internal/pkg/plugin/devlake/create.go
internal/pkg/plugin/devlake/devlake.go
internal/pkg/plugin/devlake/read.go
internal/pkg/plugin/devlake/update.go

State getting logic enhancement with devlake plugin.
1. Add values.yaml config to DevStream state; 
2. Add *devlake url* to outputs.
N/A
- config
```yaml
---
varFile: "" # If not empty, use the specified external variables config file
toolFile: "" # If not empty, use the specified external tools config file
pluginDir: "~/.devstream/plugins"
state: # state config, backend can be local or s3
backend: local
options:
---
tools:
- name: devlake
dependsOn: [ ]
options:
repo:
name: devlake
url: https://merico-dev.github.io/devlake-helm-chart
chart:
chartPath: ""
chartName: devlake/devlake
version: ""
releaseName: devlake
namespace: devlake …
```

Feat: State Getting Logic Enhancement with DevLake Plugin

---

.github/workflows/automated-release.yml
.github/workflows/cf-ip-monitor.yml
.github/workflows/e2e-test.yml
.github/workflows/license-scan.yml
.github/workflows/link-pr.yml
.github/workflows/link.yml
.github/workflows/lint-commit-message.yml
.github/workflows/pr.yml
.github/workflows/update-fig-spec.yml

Use the private github acionts runner to improve packaging speed, except for Mac-related builds. mac-related (including m1 chips and intel chips) builds will not use the private method for now.
Improved packaging speed, no waiting for GitHub scheduling, and increased concurrency because it runs as an automatically scalable k8s runner

feat: use a self-hosted GitHub actions runner that runs as a crd for k8s

---

.github/workflows/e2e-test.yml

Since we were using the public GitHub actions, aws-cli is already included in the GitHub public runner, but now we are using the self-hosted k8s crd runners, we need to install aws-cli ourselves
install AWS-Cli for self-hosted runners before config AWS credentials

fix: install aws-cli for self-hosted runners

---

pkg/util/scm/git/repoinfo.go
pkg/util/scm/github/repo.go

- fix reposcaffolding error when use org
- fix e2e test error
close #1183

fix: reposcaffold not valid for orgization

---

README.md
docs/development/git-workflow/reviewing.md
docs/development/git-workflow/reviewing.zh.md
pkg/util/k8s/k8s.go
pkg/util/scm/github/workflow.go

* add a new func to test functions which use `k8s.NewClient()` easily
* fix broken links

feat: set fake k8s client before calling k8s.NewClient() to test

---

internal/pkg/upgrade/upgrade.go

issues: https://github.com/devstream-io/devstream/issues/1172
Binary executable file path( /usr/local/bin/):
exec dtm upgrade other path(/root/devstreamTest)
https://github.com/devstream-io/devstream/issues/1172

[fix bug] Execute upgrade in a different path

---

staging/dtm-repo-scaffolding-java-springboot/.gitignore
staging/dtm-repo-scaffolding-java-springboot/mvnw
staging/dtm-repo-scaffolding-java-springboot/mvnw.cmd

resolve https://github.com/devstream-io/devstream/issues/1228

chore: update staging folder links

---

internal/pkg/plugin/githubactions/general/create.go
internal/pkg/plugin/githubactions/general/delete.go
internal/pkg/plugin/githubactions/general/githubactions.go
internal/pkg/plugin/githubactions/general/read.go
internal/pkg/plugin/gitlabci/generic/create.go
internal/pkg/plugin/gitlabci/generic/delete.go
internal/pkg/plugin/gitlabci/generic/generic.go
internal/pkg/plugin/gitlabci/generic/read.go
internal/pkg/plugin/jenkinspipeline/create.go
internal/pkg/plugin/jenkinspipeline/delete.go
internal/pkg/plugin/jenkinspipeline/read.go
internal/pkg/plugin/jenkinspipeline/validate.go
internal/pkg/plugin/jenkinspipeline/validate_test.go
internal/pkg/plugininstaller/ci/ci.go
internal/pkg/plugininstaller/ci/ci_test.go
internal/pkg/plugininstaller/ci/step/general.go
internal/pkg/plugininstaller/ci/step/general_test.go
internal/pkg/plugininstaller/ci/step/language.go
internal/pkg/plugininstaller/ci/step/step.go
internal/pkg/plugininstaller/ci/step/step_test.go
internal/pkg/plugininstaller/ci/validate.go
internal/pkg/plugininstaller/ci/validate_test.go

- add ci language default options
- extract common logic in ci
#1215

refactor: use more general ci config

---

internal/pkg/configmanager/config.go
internal/pkg/configmanager/config_test.go
internal/pkg/configmanager/configmanager.go
internal/pkg/configmanager/configmanager_test.go
internal/pkg/configmanager/rawconfig.go
internal/pkg/configmanager/tool.go

`configmanager` package enhancement
N/A
N/A

Refactor: `configmanager` Package Enhancement

---

internal/pkg/configmanager/config.go
internal/pkg/configmanager/configmanager_test.go

To make sure dtm will execute origin tools first, then tools from apps.

feat: all tools from apps depend on origin tools

---

internal/pkg/plugin/argocdapp/tpl/argocd.tpl.yaml
internal/pkg/plugin/installer/kubectl/installer.go
internal/pkg/plugin/installer/kubectl/installer_test.go
internal/pkg/plugin/installer/reposcaffolding/installer.go
internal/pkg/plugin/installer/reposcaffolding/option.go
internal/pkg/plugin/installer/reposcaffolding/option_test.go
pkg/util/file/dir.go
pkg/util/file/dir_test.go
pkg/util/kubectl/cmd.go
pkg/util/kubectl/errors.go

- raise error when repoTemplate variable not exist
- kubectl does'nt rase error when error
close #1262

fix: reposcaffolding raise error when variable not exist

---

internal/pkg/configmanager/app.go
internal/pkg/configmanager/app_test.go
internal/pkg/configmanager/config.go
internal/pkg/configmanager/configmanager.go
internal/pkg/configmanager/configmanager_test.go
internal/pkg/configmanager/coreconfig.go
internal/pkg/configmanager/coreconfig_test.go
internal/pkg/configmanager/pipelinetemplate.go
internal/pkg/configmanager/pipelinetemplate_test.go
internal/pkg/configmanager/tool.go
internal/pkg/configmanager/tool_test.go
internal/pkg/configmanager/variables.go
internal/pkg/configmanager/variables_test.go
pkg/util/file/yaml.go
pkg/util/template/processor.go
pkg/util/template/processor_test.go

Fixed the bug: numeric type variables are parsed as strings
close #1260
bugfixed
`foo: [[ var1 ]]/[[ var2 ]]` support @steinliber 
- config
```yaml
config:
state:
backend: local
options:
vars:
gitlabHostname: gitlab.example.com
jenkinsHostname: jenkins.example.com
harborHostname: harbor.example.com
harborURL: http://harbor.example.com
jenkinsAdminUser: admin
jenkinsAdminPassword: changeme
gitlabSSHPort: 30022
gitlabHttpPort: 30080
gitlabHttpsPort: 30443
tools:
- name: gitlab-ce-docker
dependsOn: []
options:
hostname: [[ gitlabHostname ]]
gitlabHome: /srv/gitlab
sshPort: [[ gitlabSSHPort ]]
httpPort: [[ gitlabHttpPort ]]
httpsPort: [[ …
```

fix: numeric type variables are parsed as strings

---

internal/pkg/plugin/helminstaller/create.go
internal/pkg/plugin/helminstaller/defaults/defaultconfig.go
internal/pkg/plugin/helminstaller/delete.go
internal/pkg/plugin/helminstaller/helminstaller.go
internal/pkg/plugin/helminstaller/helminstaller_test.go
internal/pkg/plugin/helminstaller/read.go
internal/pkg/plugin/helminstaller/update.go

e.g. instanceID="argocd-config-001", "argocd" and "argocd-config" both are supported helm charts, then dtm should know that it is a argocd-config instance.
N/A
instanceID becomes more accurate in helm-installer plugin.

fix: greedy matching problem of helm-installer plugin

---

docs/core-concepts/config.md
docs/core-concepts/overview.md
docs/core-concepts/tools-apps.md
docs/development/git-workflow/reviewing.md
docs/development/git-workflow/reviewing.zh.md

docs: update app-centric docs

---

internal/pkg/configmanager/variables.go
internal/pkg/configmanager/variables_test.go
pkg/util/template/processor.go
pkg/util/template/processor_test.go
pkg/util/template/render.go

before:
```yaml
token1: [[ env GITHUB_TOKEN]]
token2: [[ env "GITLAB_TOKEN" ]]
```
rendered:
```yaml
token1: token_value_xxx
token2: token_value_xxx
```

feat: support env vars

---

test/e2e/yaml/e2e-apps.yaml

test: fix apps e2e

---

internal/pkg/plugin/installer/ci/ci.go
internal/pkg/plugin/installer/ci/ci_test.go
internal/pkg/plugin/jenkinspipeline/option.go
internal/pkg/plugin/jenkinspipeline/tpl/Jenkinsfile_offline.tpl
internal/pkg/plugin/jenkinspipeline/validate.go

- jenkins support new option `offline` for config offline
- jenkins will not check and install plugins, so you need to build a jenkins image with plugins instqalled first
- jenkins will not use global share library, instead we upload Jenkinsfile to repo 
- jenkins will check plugins and automatic install plugins 
- jenkins will use sharelib for common jenkins step
#1239

feat: jenkins pipeline support offline

---

docs/best-practices/air-gapped-jenkins-pipeline.zh.md
internal/pkg/show/config/plugins/jenkins-pipeline.yaml

- add docs for jenkins-pipeline offline options
#1239

fix: add docs for jenkins-pipeline offline options

---

docs/core-concepts/apps.zh.md

docs: add app config detail docs

---

internal/pkg/configmanager/pipelineDefault.go

- use https to get github-actions file
- pass e2e test for github action doesn't has public key
#1239

fix: e2e test error in ci file getter

---

docs/core-concepts/output.md
docs/plugins/argocdapp.md
docs/plugins/repo-scaffolding.md
examples/gitops.yaml
examples/quickstart.yaml
internal/pkg/plugin/installer/reposcaffolding/installer.go
internal/pkg/show/config/plugins/repo-scaffolding.yaml
internal/pkg/show/config/templates/gitops.yaml
internal/pkg/show/config/templates/quickstart.yaml
test/e2e/yaml/e2e-test-local.yaml

Fix the quickstart workflow failed with var ImageRepo error 
close #1298 
bugfixed

Fix: Quickstart Workflow Failed With var ImageRepo Error 

---

docs/best-practices/gitops.md
docs/best-practices/gitops.zh.md
docs/plugins/argocdapp.md
docs/plugins/plugins-list.md

docs: translate gitops

---

docs/plugins/argocdapp.md
internal/pkg/configmanager/app.go
internal/pkg/configmanager/app_test.go
internal/pkg/configmanager/appspec.go
internal/pkg/configmanager/config.go
internal/pkg/configmanager/config_test.go
internal/pkg/configmanager/configmanager_test.go
internal/pkg/configmanager/pipelineDefault.go
internal/pkg/configmanager/pipelineDefault_test.go
internal/pkg/configmanager/pipelinetemplate.go
internal/pkg/configmanager/pipelinetemplate_test.go
internal/pkg/plugin/argocdapp/create.go
internal/pkg/plugin/argocdapp/delete.go
internal/pkg/plugin/argocdapp/options.go
internal/pkg/plugin/argocdapp/options_test.go
internal/pkg/plugin/argocdapp/read.go
internal/pkg/plugin/argocdapp/state_test.go
internal/pkg/plugin/argocdapp/validate.go
internal/pkg/plugin/argocdapp/validate_test.go
internal/pkg/plugin/installer/ci/cifile/state.go
internal/pkg/plugin/installer/reposcaffolding/utils.go
internal/pkg/show/config/plugins/argocdapp.yaml
pkg/util/scm/scm.go
test/e2e/yaml/e2e-apps.yaml
test/e2e/yaml/e2e-test-local.yaml
test/e2e/yaml/e2e-tools.yaml

- support share `imageRepo` config `ci` stage with `cd` stage, we only need one `imageRepo` config for now
- add more `ut` for `configmanager` module and `argocdapp` module
- update e2e test 
- use repo-scaffolding without helm configs
close #1296

feat: pass variable from ci to cd

---

cmd/devstream/apply.go
internal/pkg/configmanager/configmanager.go
internal/pkg/configmanager/rawconfig.go
internal/pkg/configmanager/rawconfig_test.go

Config:
```yaml
asdf
```
Original behaviour:
```bash
tiexin@mbp ~/work/devstream-io/devstream $ ./dtm apply
2022-12-08 11:15:00 ℹ [INFO]  Apply started.
2022-12-08 11:15:00 !! [ERROR]  Apply failed => configmanager can't found valid [config], please check your config file.
```
After fix:
```bash
tiexin@mbp ~/work/devstream-io/devstream $ ./dtm apply
2022-12-08 11:27:27 ℹ [INFO]  Apply started.
2022-12-08 11:27:27 !! [ERROR]  Apply failed => config not valid; check the [config] section of your config file.
2022-12-08 11:27:27 ℹ [INFO]  It seems your config file is not valid. Please check the official documentation https://docs.devstream.io, or use the "dtm show config" command …
```

chore: logging improvement for invalid configuration

---

hack/release/auto-release-darwin-arm64.sh

check if the number of plugins on s3 is correct.
By calculating the total number of local plugin files and comparing it with the total number of plugins in the corresponding directory of s3 (minus the number of dtm files for 3 platforms, i.e. 3), if they are not equal, an error message is returned after script execution.
I took out the relevant pieces of logic in the script, named it a test script, and tested the results as follows:

feat: check if the number of plugins on s3 is correct

---

.github/sync-staging-repo.yml
.github/workflows/sync-staging-repo.yml
staging/README.md

sync repos under staging folder to individual repos
close #1333
@daniel-hutao 
Please setup `GH_PAT` repo SECRET according to https://github.com/BetaHuhn/repo-file-sync-action/discussions/31#discussioncomment-674804
(Or we can use github app to generate tokens, ref: https://github.com/marketplace/actions/repo-file-sync-action#token)

feat: sync repos under staging folder to individual repos

---

.gitignore
cmd/devstream/show.go
examples/apps.yaml
internal/pkg/show/config/config.go
internal/pkg/show/config/embed_gen.go
internal/pkg/show/config/gen_embed.tpl
internal/pkg/show/config/templates/apps.yaml

`dtm show config --template=apps`

feat: add apps template to dtm show config

---

.gitignore
cmd/devstream/show.go
docs/best-practices/apps.md
docs/best-practices/apps.zh.md
examples/apps.yaml
internal/pkg/show/config/config.go
internal/pkg/show/config/embed_gen.go
internal/pkg/show/config/gen_embed.tpl
internal/pkg/show/config/templates/apps.yaml
mkdocs.yml

A new Doc for GitOps using Apps.

Docs gitops for apps

---

docs/best-practices/apps.zh.md

docs: gitops-apps cn

---

staging/dtm-repo-scaffolding-golang-gin/Dockerfile.tpl
staging/dtm-repo-scaffolding-golang-gin/cmd/_app_name_/main.go.tpl
staging/dtm-repo-scaffolding-python-flask/Dockerfile.tpl

- All staging repo-scaffolding use same port 80

fix: staging reposcaffolding using 80 port as default

---

go.mod
pkg/util/template/client.go
pkg/util/template/client_test.go

- we use `[[ env ENV_KEY ]]` for the config option, for now, this pr will raise an exception when env value is not exist
#1211
when env is not set

feat: raise err when config env is not exist

---

docs/use-cases/gitops-python-flask/2-github-dtm-apps.md
docs/use-cases/gitops-python-flask/3-github-dtm-tools.md

docs: python flask gitops use case with tools

---

docs/core-concepts/config.md
docs/core-concepts/config.zh.md
internal/pkg/plugin/trello/options.go
internal/pkg/plugin/trello/state.go
internal/pkg/plugin/trello/trello.go
internal/pkg/plugin/trello/validate.go
internal/pkg/plugin/trello/validate_test.go
internal/pkg/show/config/plugins/trello.yaml
pkg/util/trello/trello.go
test/e2e/yaml/e2e-trello-config.yaml

feat: trello plugin use env to set apiKey and token

---

docs/plugins/trello.md
docs/use-cases/gitops-python-flask/2-github-dtm-apps.zh.md
docs/use-cases/gitops-python-flask/3-github-dtm-tools.md
docs/use-cases/gitops-python-flask/3-github-dtm-tools.zh.md
docs/use-cases/gitops-python-flask/4-gitlab-dtm-apps.zh.md

Translate "GitHub + GitHub Actions with DTM Tools" and "GitHub + GitHub Actions with DTM Apps"
N/A
Documents updated only.

docs: translate github-dtm-apps and tools

---

docs/use-cases/gitops-python-flask/4-gitlab-dtm-apps.md

Translated based on Bird's version.

docs: gitlab python flask use case in chinese

---

internal/pkg/upgrade/upgrade.go

Signed-off-by: Shuimo03 <wu1998102@gmail.com>
Because the GitHub releases URL was slow to download before, switching to AWS S3 will change the download speed.
before:
now
issuees:https://github.com/devstream-io/devstream/issues/1314

build:Modify GitHub releases URL to aws s3

---

internal/pkg/start/tool/argocd.go

```
❯ minikube delete
🔥  正在删除 docker 中的“minikube”…
🔥  正在删除容器 "minikube" ...
🔥  正在移除 /Users/lhp/.minikube/machines/minikube…
💀  Removed all traces of the "minikube" cluster.
❯ go run ./cmd/devstream start
I'll prepare some tools for you.
Let's get started.
✅ Docker is ready.
😄  Darwin 13.1 (arm64) 上的 minikube v1.29.0
✨  自动选择 docker 驱动
📌  Using Docker Desktop driver with root privileges
❗  Local proxy ignored: not passing HTTP_PROXY=http://127.0.0.1:7890 to docker env.
❗  Local proxy ignored: not passing HTTPS_PROXY=http://127.0.0.1:7890 to docker env.
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3885MB) ...
❗  Local proxy ignored: not passing HTTP_PROXY=http://127.0.0.1:7890 to docker env.
❗  Local proxy …
```

chore: use exec to reduce helm log

---

.github/workflows/ci.yaml

Github Actions looks Golang version 1.20 as 1.2, so the workflow failed.
1.20 -> "1.20.3" works fine.
Thanks to @aFlyBird0 very much for the helping in the fix progress.

Fix The CI Error With Wrong Golang Version

---

cmd/commit.go
cmd/patch.go
cmd/scaffold.go
internal/pkg/commit/commit.go
internal/pkg/commit/commit_test.go
internal/pkg/patch/patch.go
internal/pkg/patch/patch_test.go

Implement the `dtm commit -m "commit message here"` command.

Feat: Add `dtm commit -m` Command Implementation

---

cmd/commit.go
cmd/patch.go
cmd/root.go

Fix `dtm commit` Command Cannot Get The Message From -m Flag
